In [322]:

!pip3 install textract

Collecting textract
  Downloading textract-1.6.1.tar.gz
Collecting argcomplete==1.8.2 (from textract)
  Downloading argcomplete-1.8.2-py2.py3-none-any.whl
Collecting chardet==2.3.0 (from textract)
  Downloading chardet-2.3.0-py2.py3-none-any.whl (180kB)
    100% |████████████████████████████████| 184kB 3.7MB/s ta 0:00:01
Collecting python-pptx==0.6.5 (from textract)
  Downloading python-pptx-0.6.5.tar.gz (7.1MB)
    100% |████████████████████████████████| 7.1MB 214kB/s eta 0:00:01
Collecting docx2txt==0.6 (from textract)
  Downloading docx2txt-0.6.tar.gz
Collecting beautifulsoup4==4.5.3 (from textract)
  Downloading beautifulsoup4-4.5.3-py3-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 5.7MB/s eta 0:00:01
Collecting xlrd==1.0.0 (from textract)
  Downloading xlrd-1.0.0-py3-none-any.whl (143kB)
    100% |████████████████████████████████| 153kB 5.4MB/s eta 0:00:01
Collecting EbookLib==0.15 (from textract)
  Downloading EbookLib-0.15.tar.gz
Collecting SpeechRecognition==3.6.3 (from textract)
  Downloading SpeechRecognition-3.6.3-py2.py3-none-any.whl (31.8MB)
    100% |████████████████████████████████| 31.8MB 40kB/s  eta 0:00:01    41% |█████████████▍                  | 13.3MB 6.4MB/s eta 0:00:03
Collecting six==1.10.0 (from textract)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting pocketsphinx==0.1.3 (from textract)
  Downloading pocketsphinx-0.1.3.tar.bz2 (29.4MB)
    100% |████████████████████████████████| 29.4MB 48kB/s eta 0:00:011   25% |████████▎                       | 7.6MB 10.8MB/s eta 0:00:03    38% |████████████▌                   | 11.5MB 5.7MB/s eta 0:00:04
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.6/site-packages (from python-pptx==0.6.5->textract)
Requirement already satisfied: Pillow>=2.6.1 in /usr/local/lib/python3.6/site-packages (from python-pptx==0.6.5->textract)
Collecting XlsxWriter>=0.5.7 (from python-pptx==0.6.5->textract)
  Downloading XlsxWriter-1.0.2-py2.py3-none-any.whl (139kB)
    100% |████████████████████████████████| 143kB 5.6MB/s eta 0:00:01
Building wheels for collected packages: textract, python-pptx, docx2txt, EbookLib, pocketsphinx
  Running setup.py bdist_wheel for textract ... done
  Stored in directory: /Users/jing/Library/Caches/pip/wheels/be/d4/29/a6c016f45dc6e57e29d45eb3bb6bfb3e0aa3b785aa369e1f2f
  Running setup.py bdist_wheel for python-pptx ... done
  Stored in directory: /Users/jing/Library/Caches/pip/wheels/d0/c6/2a/b5325620a2c5e63d9d5c19852b28a9bea25df93ca9fb95f6e5
  Running setup.py bdist_wheel for docx2txt ... done
  Stored in directory: /Users/jing/Library/Caches/pip/wheels/3b/ab/d3/03be281c00dc3bf81cd0f899b4679ee3714b36e15c4125e1bd
  Running setup.py bdist_wheel for EbookLib ... done
  Stored in directory: /Users/jing/Library/Caches/pip/wheels/30/ac/d6/20c2114079fd35a01988ac1fd2627bbb8c0d330fbde79af4dc
  Running setup.py bdist_wheel for pocketsphinx ... error
  Complete output from command /usr/local/Cellar/python/3.6.4_2/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/cb/dkvlq8wx7355sll83m06dfh80000gn/T/pip-build-6ejh8ffv/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/cb/dkvlq8wx7355sll83m06dfh80000gn/T/tmp6ctkc1iypip-wheel- --python-tag cp36:
  running bdist_wheel
  running build_ext
  building 'sphinxbase._ad' extension
  swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
  swig -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pocketsphinx
  Running setup.py clean for pocketsphinx
Successfully built textract python-pptx docx2txt EbookLib
Failed to build pocketsphinx
Installing collected packages: argcomplete, chardet, XlsxWriter, python-pptx, docx2txt, beautifulsoup4, xlrd, six, EbookLib, SpeechRecognition, pocketsphinx, textract
  Found existing installation: chardet 3.0.4
    Uninstalling chardet-3.0.4:
      Successfully uninstalled chardet-3.0.4
  Found existing installation: beautifulsoup4 4.6.0
    Uninstalling beautifulsoup4-4.6.0:
      Successfully uninstalled beautifulsoup4-4.6.0
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Running setup.py install for pocketsphinx ... error
    Complete output from command /usr/local/Cellar/python/3.6.4_2/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/cb/dkvlq8wx7355sll83m06dfh80000gn/T/pip-build-6ejh8ffv/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/cb/dkvlq8wx7355sll83m06dfh80000gn/T/pip-7mrr9cr3-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building 'sphinxbase._ad' extension
    swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
    swig -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1

    ----------------------------------------
Command "/usr/local/Cellar/python/3.6.4_2/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/cb/dkvlq8wx7355sll83m06dfh80000gn/T/pip-build-6ejh8ffv/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/cb/dkvlq8wx7355sll83m06dfh80000gn/T/pip-7mrr9cr3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/cb/dkvlq8wx7355sll83m06dfh80000gn/T/pip-build-6ejh8ffv/pocketsphinx/
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [320]:
from pyelasticsearch.client import ElasticSearch
import json
import requests
import pandas as pd
import math
import numpy as np
import boto3

In [318]:
config = json.load(open('../config/configsql.json', 'r'))
aws_access_key_id=config['dev']['aws']['key']
aws_secret_access_key=config['dev']['aws']['secret']
region = 'us-east-1'
endpoint = config['dev']['endpoint']
bucketname=config['dev']['bucketname']['bucketname']
index_name1 = 'candidates_cv'
index_name2 = 'parsed_resume'
es = ElasticSearch(endpoint, port=443)
comprehend = boto3.client(service_name='comprehend',aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key,region_name = region)

In [319]:
comprehend = boto3.client(service_name='comprehend',aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key,region_name = region)

# all dict

In [309]:
d_all = es.search(index = index_name1, query={
                                     "query": {"match_all": {}},
                                     "size":  622
                                     })

In [310]:
all_user = {}
for i in range(len(d_all['hits']['hits'])):
    user = d_all['hits']['hits'][i]['_source']
    id = d_all['hits']['hits'][i]['_id']
    all_user[id] = user

In [316]:
print(user)

{'name': 'Joyce Yuqiao', 'email': 'ydong26@illinois.edu', 'phone': '217-281-2176', 'education': 'University of Illinois at Urbana-Champaign May 2014\nMaster of Science, Statistics GPA: 3.74/4.00\nSun Yat-sen University (SYSU), Guangzhou, P.R. China June 2012\nBachelor of Science, Information and Computational Science GPA: 3.54/4.00\nPROJECT EXPERIENCE\nKaggle Competition: Recognize Users of Mobile Devices from Accelerometer Data 11/2013 - 12/2013\nCorrectly determined whether the 90,000 accelerometer recordings belong to the proposed 387 devices by classification\nmodels and the accuracy is up to 75%\nImplemented KNN, Naï¿½ve Bayes, Random Forest algorithms on 1 GB training data, efficiently reduced computation\ncost by performing sampling techniques\nStatistical Consulting: Survey Design Based on Statistical Analysis 02/2014 - 04/2014\nDetected 10% irrelevant and 15% highly similar questions from 78 survey questions by Factor Analysis and\nHierarchical Clustering Analysis, presented findings and delivered interpretation documents to clients\nData Mining: Role Discovery in Information Network 03/2013 - 05/2013\nAutomatically discovered the most important citation for a proposed paper, mined the association between 1.57 million\npaper and its citations with meta-path algorithm, improve predict accuracy from 33% to 67%, conducted data extraction,\ndatabases querying and large-scale matrix computation on Matlab and MySql\nPROFESSIONAL SKILLS\nTools: SAS Advanced Programming Certificate, SAS Forecast Studio, SAS Enterprise Miner, SAS Visual Analytics,\nJMP, R, MATLAB, Microsoft Excel\nProgramming Languages: C/C++(26 months), SQL', 'experience': "________________________________________\nSteelcase Inc, Advanced Analytics, Grand Rapids, MI\nAdvanced Analytics Modeler 07/2014 - Present\nDevelop and maintain an 18-month forecast for manufactory plants human resource, reduced operation cost and\nincreased reliability in manpower planning for seasonal aspects, the final accuracies are above 85%\nDevelop large-scale top-down hierarchical forecast models for weekly Sales & Operation Planning (SOP), over 10,000\nmodels at the lowest level, build models such as ARIMAX , Seasonal Exponential Smoothing models, provide data\ninsight for demand and supply balance\nSwift ability to extract, manipulate, visualize and communicate upon large datasets, developed fully-automated\nmonthly production models using SAS Stored Process and web-based visualizations using SAS Visual Analytics\nEnergetic self-starter with strong communication skills: provided analytic guidance and assess clients' need as an\ninternal statistical consultant, gave project presentations to IT leaders, provided clear assignments to interns as a mentor\nAnheuser-Busch InBev, Bud Analytics Lab, Champaign, IL\nData Analytics Intern 01/2014 ï¿½ 07/2014\nCaptured potential lost sales, detected root cause of out-of stock and provided solutions for model improvement by\nanalyzing predictions vs. actual sales patterns and evaluating the accuracy of the existing models\nBuilding daily sales predictive model for over 100 products, 4000 stores in North America for better avoiding\nout-of-stock and raising sales revenue, final predict accuracy was up to 78%\nGraduate School of Library and Information Science, University of Illinois at Urbana-Champaign\nResearch Assistant 06/2013 - 08/2013\nConducted data pre-processing in SAS, developed numerous variables creating programs to reach a final data\nGenerated quantitative tables and descriptive plots for Community Informatics Analysis researchKaggle Competition: Recognize Users of Mobile Devices from Accelerometer Data 11/2013 - 12/2013\nCorrectly determined whether the 90,000 accelerometer recordings belong to the proposed 387 devices by classification\nmodels and the accuracy is up to 75%\nImplemented KNN, Naï¿½ve Bayes, Random Forest algorithms on 1 GB training data, efficiently reduced computation\ncost by performing sampling techniques\nStatistical Consulting: Survey Design Based on Statistical Analysis 02/2014 - 04/2014\nDetected 10% irrelevant and 15% highly similar questions from 78 survey questions by Factor Analysis and\nHierarchical Clustering Analysis, presented findings and delivered interpretation documents to clients\nData Mining: Role Discovery in Information Network 03/2013 - 05/2013\nAutomatically discovered the most important citation for a proposed paper, mined the association between 1.57 million\npaper and its citations with meta-path algorithm, improve predict accuracy from 33% to 67%, conducted data extraction,\ndatabases querying and large-scale matrix computation on Matlab and MySql\nPROFESSIONAL SKILLS\nTools: SAS Advanced Programming Certificate, SAS Forecast Studio, SAS Enterprise Miner, SAS Visual Analytics,\nJMP, R, MATLAB, Microsoft Excel\nProgramming Languages: C/C++(26 months), SQL"}

# parsed resume

In [294]:
def extract_information(user_record):
    resp = {}
    for element in ['education', 'summary', 'projects', 'experience']:
        if element in user_record:
            text = user_record[element]
            #print(element,len(text))
            entity = comprehend.detect_entities(Text=text, LanguageCode='en')
            keyword = comprehend.detect_key_phrases(Text=text, LanguageCode='en')
        else:
            entity = {}
            keyword = {}
        resp[element] = {"entities": entity, "keywords": keyword}
    return resp

In [2051]:
def ASCII(s):
    if s is None:
        return ''
    s2 = ''
    for i in range(len(s)):
        x = ord(s[i])
        if x >= 32 and x < 128:
            s2 += s[i]
        else:
            s2 += ' '
    return s2

In [2052]:
resp_all = {}
for id in all_user.keys():
    print(id)
    user = all_user[id]
    for key in user.keys():
        user[key] = ASCII(user[key])
        if len(user[key]) > 5000:
            user[key] = user[key][0:5000]
    result = extract_information(user)
    resp_all[id] = result

https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_B. TolgaOztanResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_MarkoBokulic_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Prasuna_Duggirela_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Karan Kapoor - Data Science - Carnegie Mellon University.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Data Science, Inc..pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Bo_Peng.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Arun Varghese Resume 2-15.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume 2016 Joyce Dong April.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeIjazAhamedMeeranAbdulJabbar.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeStefanSolntsev.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeAmrutaKulkarni.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Clara_Hyunyoung_Shin_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV_cover.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Karen Blakemore Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_LIN, TIFFANY RESUME.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Muskan Kukreja_CV_pdf.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeMinshanCui.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resum.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Lanhao_Chen.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeDaiChen.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ChristianWidmer.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Fournier_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Cover_Letter_Data_Skeptic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Mohit_Dayal_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_rruelas_cv_new.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced___PWFILES505_RedirectedFolders$_c055035_Desktop_Adam_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Xi Wang resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume13.0.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_fe22c9ec.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Xie He Resume_10_15_objective_data_mining.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeShuHuang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume & Cover Letter copy.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-Srikanth-Vadde-PhD-Operations Research.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resumeAndCL_DataScience.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_jtapia_resume_20151013.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_KanaWatanabe-2016-FINAL.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_TrilokyaAkula_Resume_2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_skelly_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_c3db463e.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Hakan_Kizilocak_Ph_D.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_MeiDuanmu.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_mf-resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_f35f2547.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Salil_Navgire_Resume_2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_TejaR1.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_b2ae364d.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_coverletter_Hamilton_2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_c85d5272.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Updated_Resume_Ayan.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_aee1411d.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Time Series Analysis of Air Pollution CO in California South Coast Area, with Seasonal ARIMA Model and VAR Model.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_data_10-12_CA.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_rezakhoieresume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Data_Scientist.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_DamienBenvenisteCV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_d3863ff0.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeShuaiZheng (1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Victor Amaral Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_XiaoangZhang_Resume_F.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Tartakovsky April 2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_DS LTX Pradeep.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Sanling_Song_1757332.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_afb1de38.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ManuelAmaya.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_CV(new).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_aa9611aa.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeletianZhao.pdf.txt

https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Srikar_G.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_minshan.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Zhonglin-jobs-resume_new.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume DA 2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Liang_Gao_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_PrauseResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Shahram Farhadi Nia Resume_2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_anurag_panwar_pub.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_1 (1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_cv copy.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Vicky(Siliang).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Shu_Liu_1757332(1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeVishalJoshi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Sowmya.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Srikar_Velichety_DataMining.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_JHY_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Gregory-Chu-Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Thomas Leung Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_MinaRanjbaranCV2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume (3).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-BenAssa.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Khushboo Tiwari.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_MichaelTiernay.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume for Sean Salleh 2015-09-30.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeGauravChaudhari.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_PengZeyang (1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Supreeth Meka_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_SVDAresume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_cv copy 2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_AHANA MUKHERJEE_data_scientist_ca.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_937cda41.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_8b53fb52.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_80f29c4a.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_9fc58776.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_84873804.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_471aec37.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_58e13553.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_74de8f04.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_5b153814.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_3c8adaf0.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_92725d10.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_992c5a90.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_8cbb74ff.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_471689c8.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_85c5bccf.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_6ef68acb.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_783065f7.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_327a82ab.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Adhi Rajaprabhakaran - DataSkepticResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_2-13-16 resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_01 24 2016 CV_DS.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_29534c1d.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_26dedd21.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Jo Hu CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume -- Siwei Chen.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Jitesh_Chawla_1757332.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_MhdFadhil C.V.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Fan Yu_2015O_ds.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Hassan Resume .pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Abiy_Tekola_wordnpT.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume of Shennan Lu.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume Naman Doshi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Dhillon-academicResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Charalampos_Papadimitriou_IDXResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Chidambara Natarajan Gopal resume_two_pages.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Aravind_Subramoney_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Asosa.Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume -- huan meng.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_AliceXiong_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeXueqingLi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Chen-Hsi_Huang_1757332.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Eugene_Park_resume.pdf.txt

https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume of Ramakrishnan, Vijay Thyagarajan_Analyst.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_RESUME-CHIRAG_SUBRAMANIAN_CHARLES_RIVER.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Qin_Wen.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_LONGPEI_RESUME_UPDATED.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Ankit_resume-FA (1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Nikita_Kirnosov_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Adharsh Rajendran_31Dec.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_cd6a7671.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_d072b90c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_joe_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_d839c5bc.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_0216.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_e4fe04cb.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_QianboWang_v2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_cv_Jialu_Li.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Jian Shi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume-Jyotika Singh.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_be66fe4c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Shrieraam Sathyanarayanan.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeDataSci31March2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Ryan's Resume 2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume copy 3.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resumeyongjianbi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Rajagopal-ML.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume - Kho.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Ranga_Raghunathan - Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_RESUME - Kaiyan.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Kalyanee_Chendke_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_yuanyuan_9-11-2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_c29aeb0c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Syed Mohammad Ali Shah2_21.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Parikshit_Verma.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_cover letter&resume_DataScience.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Junsong_Zhao_10082015_m_phd.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume - Rishabh Bindal.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume Zhaoxiang Chen.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_2015_Hamilton.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume copy 9.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_updated_sgupta_1.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_a6d3399a.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ed09fb38.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_jinghan yang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_LauraAngelescu_2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume Update Oct2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Sayan_Maity.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_NazilaResumeFeb3 (1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_C.V.-YChiu-2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Divyansh_Jain_Resume_Summer16Intern.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume Zijiao Chen.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumePratyushProddutur.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Pan Li_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Richard Galbo Data Science.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ShonketRay_CV_2_2016_abv.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Jae_Lim.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_shantanu.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_f8004499.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_kranthi_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_n_Paridhi Valecha_UConn_Jan 16.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_linli_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Rishabh_Jain_Resume-DataScience.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_TCE.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume of Li Ding.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Data - Cary Greenwood - Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Talwar_Ayush_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_a0f2f8a5.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Li_27th_Oct.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Himanshu Misra_Jan27.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_RESUME MARIA MORA.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_PiyushAgarwalResume.pdf.txt

https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Curriculum_vitae.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Michal_Ben_Neria.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Fu_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeZiboWang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_RESUME.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Gowdhaman_Sadhasivam_RESUME.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_9e94608b.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_9f088375.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_8d15b6c3.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Abdoli-Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ADITYA BHONGLE CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Ahmet Tuna Bolukbasi - Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_900baadb.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_852c3291.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ASHUTOSH_BHOSLE.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_2d651d41.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_4e17c974.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_414b3aae.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Data Scientist_Changtao Hou_Ph.D. in Physics.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Andres Orozco Resume .pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_4885a982.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_50d5ed8c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_7b7d30e1.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_00e50c9c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_063c8fa4.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_15278a7b.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_pernghwaresume-4.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Yuhan Dong.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Chen-Hsi_Huang_1757332(1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CaseJohn_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_PengZeyang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume copy 7.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_shabad-sehgal-resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Arthi Rabbane_2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV_Anand_BU.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_An He Resume Columbia MA Stat.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_a895abb5.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_c364662c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeShuaiZheng.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ce4f5e74.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-SK.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_KushResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Tran Sylvia (Resume Data Skeptic).docx.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_be3cf8ba.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_8c00cd3c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_NavidBazzazian_MITSLOAN.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Yingnan (April) Xu DS.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-26.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Mihir_Mehta_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Eric Zhang Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Mohamed Moharram - Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_MDiMauro.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Yan.Gao.Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Jayant Ahalawat.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_a91737f8.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Bhaumik Patel CV v.1.3.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Vatsal_Mahajan.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeJuliaWu.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Data Scientist Resume .pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_f78b9288.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ShuaiZhengUT.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV_SSADRI_DataScience_LA_2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Ravi_Satheesh Prabu_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume- Jason Letian Zhao 2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume&CoverLetter-LI.SHUDI.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_RESUME_SAMITA_PRADHAN.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Zibo_Wang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ShruthiPrakash_Resume_02052016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_SatheeshPrabuRavi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Nargess Tahmasbi Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Doug Garrett Resume.pdf.txt

https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Shashank Sharma.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_RuslanaDalinina.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Samet_Keserci_Sept29.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV_RaptisK-2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeSubramanianVellaiyan.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-SanginKim.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Yilun_Wang2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Kevin_Tran.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume copy 10.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_KenDoppResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Sanjana_Resume_Fall2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Kyeong-resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Peter Burton McCue Resume Dec 2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_MarkoBokulic_coverLetter.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Lilly_Andrew_Resume_2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeBharathJagadish.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Sneha.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_RESUME Carishma_Arun Shetty.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Prabhat_Ratnala.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Chengwei Su Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume Yifan Zhang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_XiaoangZhang_Resume_1215.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Dennis SutoCAS2016h(           phone 2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_HongyuanLu.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Tyler_Gording.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Tartakovsky 2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Hooshmand_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume copy 8.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Sean Smith Resume April 2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Venkatesh_Curriculum_vitae.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Bingchen_Liu.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_SParab.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Samet_Keserci.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeChenxiWang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Swathi CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Bhargav_Bhushanam_resume_ds_cf2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_JayKim_U_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume (1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Jan2016_YuantingChen.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_NickStucky-Mack.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume - Khushan Adatiya.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Chen_Huang_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Chen Chen-Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Data Scientist Pengbo Li.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Trinadh CV3.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Rupesh_resume_coverletter_UNCC.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Tian.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_f065d0d0.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_kevin jacobs.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_c8937218.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_Nupur_Gulalkari.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_industryResume_datascience.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_d37bd03c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Raj_Pasari_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_YM_PARK_RESUME.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_cv_Farzaneh.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_1.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Vivian Mccombs Resume _v8.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_SuwodiDBordoloi.DataScientist.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_mohamed fazeen issadeen.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume copy 6.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_e4c2fe3b.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_cv_sebastian_carron_data_science.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeYifanYang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_YanbinLu.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeJieHu.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_ran_wei.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeJerryKim.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Yuri Plotkin-SE.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_cc2981a7.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Lilly_Andrew_DS_2016.pdf.txt

https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_7cff1979.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Adam Velez Resume .pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_965a2b8d.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeMohammadNiknazar.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_6084aa80.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_48dcbbee.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_41a0dbe2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_38375814.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_51b75f0d.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_183808f1.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_20532dcd.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_203f6e92.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_17fb2e82.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_(Resume).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_00a7d5ee.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_15-0222McGeheeCV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_JaredRay_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_a76d08a2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Chaykowsky_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_DavidHerman.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Sashank Santhanam V-3.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Sumit_Rane.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Noah Burbank Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Dingchao_Zhang_DataScientist.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Xiaoxi_Xie.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_LuisSanchez.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_EvanSadlerResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Suhua Wei.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_SoumyaGowda_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_PramitChoudhary.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_XiaokeFeiResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Juan Wang_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeRobertEspinoza.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV_Nitin.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Yiqian Jin_1111_research.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_JuanWeiResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_SwethaSubramanianCVnew.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeYiLi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Yixin_Li_0222.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeGagandeepSingh.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Jean Garcia-Gathright 2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_KarthikKiran-Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeSureshJayaraman.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Rajiv_Kumar_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Marla_Schwartz_Nov2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-Alex Whitworth (2016-03).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Daland_Robert__Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_JASON_RESUME_DataScientist.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_DheeruDua.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Olivia_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Yidi(Mia) Wang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeAbbasHooshmand.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeNaveed.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CDjoe_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Raviteja_Gunda_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Qingbin Li Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_GPC2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Ming_Cong.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume Ryan Adrianto.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Goutham_Resume_Business Analytics.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Peter Park - Resume - Jan 2016 v2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Ankit Surjit Dhingra-Carnegie Mellon University.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Roopan_Verma.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Data Scientist Resume  (1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-Adam Owens.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_RudyGilmore.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeFT.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ShuaiZheng.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_c4ed272d.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Marc Harper -- Resume _ CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Philip Munyua_Resume.pdf.txt

https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_QianYao-Data-Science-Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Maxim.Arap.Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume JP.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume - Plotner_Rhett.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Amith_Mandula_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume copy.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Daniel_Kim_1757332.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Peter Park - Resume - Jan 2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Arash_Abbasi_04_2016_PhD_1.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_M_Bedi_Egilmez_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Rajagopal_Masters-FT.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Gaoang Wang Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_NehaAgarwal_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Bilal Shaw from CyberCoders.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Barry_Irick.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Margreth Mpossi-Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Curriculum Vitae_data.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Ashwini_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Renata Ghisloti CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Rohan Uday Khambekar Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Vamshi_Medisetty_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Rohan_Gaur.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_platform.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_jnortonf_cv_DataScience.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ThomasDebeauvais.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Zuev_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Young Suk Cho CV_151014.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ParamDhillon.Kinetic.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_bd32b0da.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_edbe541c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Rupesh_resume_UNCC.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_SANDHIYA KOTHANDAN RESUME CA.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_original.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Rohan_Arora_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_samantha-wey.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Vasisht_Raghavendra_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Data_Scientist copy.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_fd2a046a.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_nururRahman Revised.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Arash-Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume(Yingjie).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Vishal_Joshi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Saurabh Trikande UCLA Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Freddy Hernandez CV & Taxi Hot Spot Paper 2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CenGuo_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume - Ikenna Ivenso.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Reza_Jafarkhani_CV_DS.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Yibing Qi Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ef60170d.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_a5b9b3db.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Nikhil_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Wei Wang's Resume(Data Scientist).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_YijiaDingResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Kaustav_Saha_US_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_e74ba5c0.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_saarthak_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Prabhat.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_SAdidamu_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Time Series Analysis of Particulate Matter 2.5 In the San Joaquin Valley.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_801ca434.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Akansha Sharma Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Afshin Abadi (Resume).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_AjaySridharResume2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_46fc846c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_5911f22b.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_789222f3.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_9f87e98c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_47c0e23a.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_2a4fd491.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_1978d61c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_218f62aa.pdf.txt

https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_1ee4a9f0.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_2016 AllenKatz_CV Data Scientist.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_249d5333.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_28b2c4c1.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_2fab213d.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_full_version2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_b6f2c5b9.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Anup_Kalia.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeMadihaHussain.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Fulya_Ozcan_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Lei Shao.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Allen_Lee_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume - Matthew OConnell.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Sam.Nolen.Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-Benita Vaz.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_PriyankaBiswas_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Avi_Sanadhya.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV_VerII.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Kavya Nagaraj Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Kudriavtseva_resume2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-Mengyi Gao.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Lindenblatt_Data_Science_Application.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume (2).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_DiegoVResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resumemohdzakaria.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume-Heather Li.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume Data Scientist Manager.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_HanchaoLiu.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_CURRENT.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Duong, SQ Resume DataScience Data Scientist.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Mafaaz Siddiqui Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume copy 2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Manish_Chaurasia.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Debasish_Das_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Roozbeh_Resume_April16.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume Short -- Siwei Chen.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Mengyuan Huang_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Shanshan_Su_1757332(1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_b2c75e42.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_SixiangFan.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume - Yiwei Cai.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_RESUME_AR.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Sandhiya_updatedResume_March10.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ChengLuocv (1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Cheng_Xijin_xc2295_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Barry-Barriosver3.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_DSouza_Justin_Resume_N.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Jason_Kaszpurenko.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_MaryamNajafianResearchScientist_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Prakanshu Bajpai.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Midhun_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_C__Users_Kristina.Console_Desktop_Kristina_Salary Support_Kristina's Resume 2015_executive Finance.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeJasonKaszpurenko.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV_Liu Mingyang.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_YossofEshaqResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_KristiAngelResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Hossein Sadeghi - Data Analytics.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_QianboWang_v5.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeSrikarG.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ResumeZheLi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Chithra_Srinivasan_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_SHRUTHI_BATHINA_Resume_UConn.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_BHARATH - Resume - oct 2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Debjit Nayak_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV_Julien_Nel_2016.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_99b3a9cd.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_DSouza_Justin_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Hisham-Kamal-Sayed-Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_CV_GinaEscobar.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_HayoungSeo_resume.pdf.txt

https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_GeorginaTolgosResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Daniel_Kim_1757332(1).pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_XSS_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Tejapr6.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_Le.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_patri_resume1pg.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_kts_resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume (1) copy.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_krivanw.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ruby childs.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_MamtaKanvinde.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume copy 5.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Wentao's Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_agharkar-cv.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_SureshJayaraman_PD.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_b0bfb7e2.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_gvalk_en_slim.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_LauraAngelescu_2015.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_c356cd8c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Layla_Tadjpour.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_VikashGupta_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Shreyasi Parkhi.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume Data Science.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Muthu_Arumugam.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_cef2e941.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_a549ce52.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Karthik-Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_aromalyn.cv.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Satish_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Principal Data Scientist- Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_a5adb54c.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Heng(Harper) Fang_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ed18664b.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_choe, joseph - resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ab9bca32.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Sumit_Rane_PA.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_https___raw.githubusercontent.com_techacolyte42_public-relations_programming-short_WilsonConnorResume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ff3c59c4.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume copy 4.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_adeel.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_copy.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_3e45bb9e.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_8b833eeb.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_530fdf2a.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Adwait__Kirtikar.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_AnkoorB_Data_Science_Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Adam Chaffee Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Amitoj Singh Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Aashirwad Anand 2015-12-18.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_ANDONIS_MITIDIS_CV.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_AJohnson Resume.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_AndreYoon_Resume_20160110.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_29ad2b65.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_4d8cc9f8.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_3edf2b04.pdf.txt
https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_6b534f53.pdf.txt

In [305]:
len(resp_all)

NameError: name 'resp_all' is not defined

# update to elasticsearch

In [2056]:
for id in resp_all.keys():
    user = resp_all[id]
    result = es.index(index_name2,'parsed_resume',user, id = id )

In [2063]:
top10 = es.search(index = index_name2, query={"query": {"match_all": {}}})

In [2095]:
top10['hits']['hits'][1]['_source']['education']['keywords']['KeyPhrases'][1]['Text'].lower()

'computing'

In [2163]:
top10['hits']['hits'][1]['_source']['education']['keywords']['KeyPhrases']

[{'BeginOffset': 0,
  'EndOffset': 8,
  'Score': 0.9637526273727417,
  'Text': 'Bachlors'},
 {'BeginOffset': 12,
  'EndOffset': 21,
  'Score': 0.9738655090332031,
  'Text': 'Computing'},
 {'BeginOffset': 23,
  'EndOffset': 30,
  'Score': 0.9676105976104736,
  'Text': 'Honours'},
 {'BeginOffset': 33,
  'EndOffset': 46,
  'Score': 0.9351752996444702,
  'Text': 'Expected 2016'},
 {'BeginOffset': 51,
  'EndOffset': 56,
  'Score': 0.984465479850769,
  'Text': 'Queen'},
 {'BeginOffset': 59,
  'EndOffset': 69,
  'Score': 0.9880484342575073,
  'Text': 'University'},
 {'BeginOffset': 73,
  'EndOffset': 79,
  'Score': 0.9994682669639587,
  'Text': 'Canada'}]

In [15]:
es.search(index = index_name2, query=
{'_source':'education.keywords.KeyPhrases.Text',
  "aggs": {
    "group_by_keyword": {
      "terms": {
        "field": "education.keywords.KeyPhrases.Text.keyword"
      }
    }
  }
})

{'_shards': {'failed': 0, 'successful': 5, 'total': 5},
 'aggregations': {'group_by_keyword': {'buckets': [{'doc_count': 198,
     'key': 'University'},
    {'doc_count': 170, 'key': 'Science'},
    {'doc_count': 86, 'key': 'GPA'},
    {'doc_count': 74, 'key': 'Machine Learning'},
    {'doc_count': 67, 'key': 'Computer Science'},
    {'doc_count': 57, 'key': 'Technology'},
    {'doc_count': 55, 'key': 'data'},
    {'doc_count': 52, 'key': 'Python'},
    {'doc_count': 50, 'key': 'Master'},
    {'doc_count': 48, 'key': 'Engineering'}],
   'doc_count_error_upper_bound': 32,
   'sum_other_doc_count': 24727}},
 'hits': {'hits': [{'_id': 'https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Updated_Resume_Ayan.pdf.txt',
    '_index': 'parsed_resume',
    '_score': 1.0,
    '_source': {'education': {'keywords': {'KeyPhrases': [{'Text': 'University'},
        {'Text': 'Washington'},
        {'Text': 'Information School'},
        {'Text': 'Seattle'},
        {'Text': 'WA Sep 2014'},
        {'Text': 'May 2016 Master'},
        {'Text': 'Science'},
        {'Text': 'Information Management'},
        {'Text': 'Focus'},
        {'Text': 'Data Science & Analytics'},
        {'Text': 'GPA'},
        {'Text': '3.76'},
        {'Text': 'Jul 2008 Jun 2012 University'},
        {'Text': 'Pune, India Bachelors'},
        {'Text': 'Engineering'},
        {'Text': 'Electronics'},
        {'Text': 'Grade First Class'},
        {'Text': 'Distinction'},
        {'Text': 'Employment Data Solutions Analytics Intern'},
        {'Text': 'The Walt Disney Company'},
        {'Text': 'Seattle'},
        {'Text': 'WA Aug 2015'},
        {'Text': 'Ongoing Working'},
        {'Text': 'YouTube API'},
        {'Text': 'Disney'},
        {'Text': 'YouTube channel owners'},
        {'Text': "' data"},
        {'Text': 'marketing analysis'},
        {'Text': 'visualization'},
        {'Text': 'business decisions'},
        {'Text': 'higher management'},
        {'Text': 'Developing code'},
        {'Text': 'Java and MySQL'},
        {'Text': 'sweepstakes'},
        {'Text': 'ESPN, ABC, Disney'},
        {'Text': 'Ice, Honda, Dior etc'},
        {'Text': 'Software Developer Intern'},
        {'Text': 'Big Data'},
        {'Text': 'Bank'},
        {'Text': 'America, Charlotte, NC Jun 2015'},
        {'Text': 'Aug 2015'},
        {'Text': 'Agile'},
        {'Text': 'Systems Engineering team'},
        {'Text': 'the Hadoop stack'},
        {'Text': 'Logging Framework'},
        {'Text': 'Hive and Pig Hands'},
        {'Text': 'experience'},
        {'Text': 'HDFS'},
        {'Text': 'Hadoop Map Reduce framework'},
        {'Text': 'Pig Macro'},
        {'Text': 'Java UDF'},
        {'Text': 'Hive'},
        {'Text': 'Pig'},
        {'Text': 'Impala'},
        {'Text': 'Oozie'},
        {'Text': 'a Cloudera Hadoop data warehouse'},
        {'Text': 'sources'},
        {'Text': 'processes'},
        {'Text': 'retail data'},
        {'Text': 'processes and transformations'},
        {'Text': 'BASEL II regulatory requirements'},
        {'Text': 'Associate Software Engineer'},
        {'Text': 'Accenture, Bangalore, India Feb 2013'},
        {'Text': 'May 2014 Client'},
        {'Text': 'State Farm Insurance Web service development'},
        {'Text': 'a part'},
        {'Text': 'ICP'},
        {'Text': 'Integration'},
        {'Text': 'Customer Platform'},
        {'Text': 'team'},
        {'Text': 'CRM Integration'},
        {'Text': 'web services'},
        {'Text': 'SFDC'},
        {'Text': 'different mainframes'},
        {'Text': 'other internal web services'},
        {'Text': 'major web services'},
        {'Text': 'requirement analysis'},
        {'Text': 'design'},
        {'Text': 'development'},
        {'Text': 'testing'},
        {'Text': 'support phases'},
        {'Text': 'Hands-on experience'},
        {'Text': 'complete software development cycle'},
        {'Text': 'Agile methodology'},
        {'Text': 'Product Implementation Consultant'},
        {'Text': 'iCreate, Bangalore, India Jul 2012 Feb 2013 Client'},
        {'Text': 'Societe Generale Integrating bank'},
        {'Text': 'core banking system'},
        {'Text': 'Finacle & Market'},
        {'Text': 'developing end-to-end ETL'},
        {'Text': 'the same'},
        {'Text': 'Hands'},
        {'Text': 'experience'},
        {'Text': 'ETL'},
        {'Text': 'Data Modeling'},
        {'Text': 'Database maintenance'},
        {'Text': 'performance tuning'},
        {'Text': 'ETL processes/databases'},
        {'Text': 'Extensive knowledge'},
        {'Text': 'Informatica mappings'},
        {'Text': 'mapplets'},
        {'Text': 'workflows'},
        {'Text': 'worklets'},
        {'Text': 'Spot Award'},
        {'Text': 'exemplary contribution'},
        {'Text': 'the company'},
        {'Text': 'Academic Projects Banking Investment Analytics'},
        {'Text': 'UW Effort'},
        {'Text': 'bank profitability'},
        {'Text': 'various products'},
        {'Text': 'different branches'},
        {'Text': 'a bank'},
        {'Text': 'investment'},
        {'Text': 'the future'},
        {'Text': 'market analysis'},
        {'Text': 'mode'},
        {'Text': 'media'},
        {'Text': 'most customers'},
        {'Text': 'a particular branch'},
        {'Text': 'investment strategies'},
        {'Text': 'advertisement Building OLTP databases'},
        {'Text': 'thousands'},
        {'Text': 'user data'},
        {'Text': 'dimensional data marts'},
        {'Text': 'ETL'},
        {'Text': 'SSIS'},
        {'Text': 'reports'},
        {'Text': 'SSRS/Tableau Predicting business future'},
        {'Text': 'trends'},
        {'Text': 'UW'},
        {'Text': 'the simple question'},
        {'Text': 'coffee joint'},
        {'Text': 'restaurant or bar'},
        {'Text': 'Seattle'},
        {'Text': 'the near future'},
        {'Text': '6 month'},
        {'Text': 'social data'},
        {'Text': 'such businesses'},
        {'Text': 'Yelp'},
        {'Text': 'their trend'},
        {'Text': 'this study'},
        {'Text': 'business future'}]}}},
    '_type': 'parsed_resume'},
   {'_id': 'https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_aee1411d.pdf.txt',
    '_index': 'parsed_resume',
    '_score': 1.0,
    '_source': {'education': {'keywords': {'KeyPhrases': [{'Text': 'Bachlors'},
        {'Text': 'Computing'},
        {'Text': 'Honours'},
        {'Text': 'Expected 2016'},
        {'Text': 'Queen'},
        {'Text': 'University'},
        {'Text': 'Canada'}]}}},
    '_type': 'parsed_resume'},
   {'_id': 'https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Time Series Analysis of Air Pollution CO in California South Coast Area, with Seasonal ARIMA Model and VAR Model.pdf.txt',
    '_index': 'parsed_resume',
    '_score': 1.0,
    '_source': {},
    '_type': 'parsed_resume'},
   {'_id': 'https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_resume_data_10-12_CA.pdf.txt',
    '_index': 'parsed_resume',
    '_score': 1.0,
    '_source': {'education': {'keywords': {'KeyPhrases': [{'Text': 'MA, Physics, University'},
        {'Text': 'Texas, Austin, GPA'},
        {'Text': '3.46'},
        {'Text': 'November 2015'},
        {'Text': 'Expected'},
        {'Text': 'BA'},
        {'Text': 'Physics'},
        {'Text': 'BS'},
        {'Text': 'Applied Mathematics'},
        {'Text': 'University'},
        {'Text': 'California'},
        {'Text': 'Los Angeles'},
        {'Text': 'GPA'},
        {'Text': '3.77 2009 U.S. Citizen Relevant Courses'},
        {'Text': 'Numerical Analysis'},
        {'Text': 'Computational Physics'},
        {'Text': 'Bayesian Statistical Methods'},
        {'Text': 'Numerical Linear Algebra Continuing Education'},
        {'Text': 'R Programming'},
        {'Text': 'Coursera'},
        {'Text': 'Data Manipulation'},
        {'Text': 'Scale'},
        {'Text': 'Systems and Algorithms'},
        {'Text': 'Coursera'},
        {'Text': 'Computational Investing'},
        {'Text': 'Coursera'},
        {'Text': 'Learning Python'},
        {'Text': 'Data Analysis'},
        {'Text': 'Visualization'},
        {'Text': 'Udemy'},
        {'Text': 'TECHNICAL SKILLS R'},
        {'Text': 'Python'},
        {'Text': 'pandas'},
        {'Text': 'numpy'},
        {'Text': 'matplotlib'},
        {'Text': 'scikit-learn'},
        {'Text': 'SQL, C++'},
        {'Text': 'Matlab'},
        {'Text': 'Linux'},
        {'Text': 'Unix'},
        {'Text': 'OpenMP'},
        {'Text': 'MPI'},
        {'Text': 'C# COURSE PROJECTS Used R'},
        {'Text': 'Markov Chain Monte Carlo simulations'},
        {'Text': 'Bayesian model'},
        {'Text': 'professional basketball data Utilized cross-validation'},
        {'Text': 'Best Subset'},
        {'Text': 'Forward Step'},
        {'Text': 'Backward Step algorithms'},
        {'Text': 'linear regression model'},
        {'Text': 'only 8'},
        {'Text': '26 original predictors'},
        {'Text': 'Used WinBUGS and R'},
        {'Text': 'Markov Chain Monte Carlo techniques'},
        {'Text': 'Bayesian regression model'},
        {'Text': 'non- informative priors'},
        {'Text': 'trace plots'},
        {'Text': 'autocorrelation plots'},
        {'Text': 'principal component analysis'},
        {'Text': 'Ridge regression'},
        {'Text': 'Lasso regression'},
        {'Text': 'further dimension reduction'},
        {'Text': 'the Best Subset'},
        {'Text': 'Forward Step'},
        {'Text': 'Backward Step algorithms PERSONAL PROJECTS NCAA tournament Kaggle competition'},
        {'Text': 'the machine'},
        {'Text': 'models'},
        {'Text': 'decision trees'},
        {'Text': 'support vector machine'},
        {'Text': 'K-nearest neighbors'},
        {'Text': 'logistic regression'},
        {'Text': 'data'},
        {'Text': 'tens of thousands'},
        {'Text': 'rows'},
        {'Text': 'the NCAA tournament Kaggle competition Crime classification Kaggle competition'},
        {'Text': 'random forest'},
        {'Text': 'linear discriminant analysis'},
        {'Text': 'a data set'},
        {'Text': 'nearly a million rows'},
        {'Text': 'crime classification Simulation'},
        {'Text': 'a card game'},
        {'Text': 'C++/C# Used C++/C# to'},
        {'Text': 'a card game'},
        {'Text': 'object-oriented programming Statistical analysis'},
        {'Text': 'programming'},
        {'Text': 'data sets'},
        {'Text': 'R and Python Used R'},
        {'Text': 'statistical analysis'},
        {'Text': 'regression'},
        {'Text': 'predictive modeling'},
        {'Text': 'data sets'},
        {'Text': 'Python'},
        {'Text': 'MapReduce algorithms'},
        {'Text': 'the Twitter API'},
        {'Text': 'the Coursera data science course'},
        {'Text': 'Python'},
        {'Text': 'time-series analyses'},
        {'Text': 'a market simulator'},
        {'Text': 'event studies'},
        {'Text': 'plots'},
        {'Text': 'PROFESSIONAL EXPERIENCE Teaching Assistant'},
        {'Text': 'University'},
        {'Text': 'Texas'},
        {'Text': 'Austin'},
        {'Text': '8/11 Present'},
        {'Text': 'Software Developer'},
        {'Text': 'Corebank'},
        {'Text': 'Seoul'},
        {'Text': 'South Korea'},
        {'Text': '11/12 11/13'},
        {'Text': 'Used C# and Silverlight'},
        {'Text': 'a custom control'},
        {'Text': 'the user'},
        {'Text': 'new buttons'},
        {'Text': 'the XAML content Used C# and Silverlight'},
        {'Text': 'a custom control'},
        {'Text': 'the user'},
        {'Text': 'objects'},
        {'Text': 'Analyzed and developed web-based applications'},
        {'Text': 'custom controls'},
        {'Text': 'Operations Research Analyst Intern'},
        {'Text': 'Applied Operations Research'},
        {'Text': '6/09 9/09'},
        {'Text': 'Utilized proprietary software'},
        {'Text': 'algorithms'},
        {'Text': 'Matlab'},
        {'Text': 'underwater acoustic propagation'},
        {'Text': 'physics-based modeling'},
        {'Text': 'ocean wave phenomena'},
        {'Text': 'plots'},
        {'Text': 'RESEARCH EXPERIENCE Research Assistant'},
        {'Text': 'University'},
        {'Text': 'Texas'},
        {'Text': 'Austin'},
        {'Text': '10/14 7/15'},
        {'Text': 'a computational physics program'},
        {'Text': 'an automated process'},
        {'Text': 'internal data structures'},
        {'Text': 'the efficiency'},
        {'Text': 'the program'},
        {'Text': 'Added C++11 features'},
        {'Text': 'the program'},
        {'Text': 'a pseudo-random number generator'},
        {'Text': 'shared pointers'},
        {'Text': 'valgrind'},
        {'Text': 'code'},
        {'Text': 'memory leaks'},
        {'Text': 'parallel programming'},
        {'Text': 'OpenMP and MPI'},
        {'Text': 'the program Research Assistant'},
        {'Text': 'University'},
        {'Text': 'Texas'},
        {'Text': 'Austin'},
        {'Text': '6/11 8/11'},
        {'Text': 'Research Assistant'},
        {'Text': 'UCLA'},
        {'Text': '3/09 12/09'},
        {'Text': 'a program'},
        {'Text': 'Monte Carlo simulations'},
        {'Text': 'a materials'}]}}},
    '_type': 'parsed_resume'},
   {'_id': 'https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_rezakhoieresume.pdf.txt',
    '_index': 'parsed_resume',
    '_score': 1.0,
    '_source': {'education': {'keywords': {'KeyPhrases': [{'Text': 'Expected Sothern Illinois University Carbondale Carbondale'},
        {'Text': 'Illinois May 2016 Master'},
        {'Text': 'Science'},
        {'Text': 'Computer Science GPA'},
        {'Text': '4.0 Relevant Courses'},
        {'Text': 'Machine Learning'},
        {'Text': 'Soft Computing'},
        {'Text': 'Big Data'},
        {'Text': 'Advanced Algorithm Design & Analysis'},
        {'Text': 'Principles'},
        {'Text': 'Virtualization & Cloud Computing'},
        {'Text': 'Advanced Parallel & Distributed Computing'},
        {'Text': 'Basic Linux System Administration'},
        {'Text': 'Data Mining/Big Data Analysis'},
        {'Text': 'Game Theory'},
        {'Text': 'Networks'},
        {'Text': 'March 2014 Iran University'},
        {'Text': 'Science and Technology Tehran'},
        {'Text': 'Iran Bachelor'},
        {'Text': 'Science'},
        {'Text': 'Computer Engineering Relevant Courses'},
        {'Text': 'Artificial Intelligence'},
        {'Text': 'Database Design'},
        {'Text': 'Discrete Mathematics'},
        {'Text': 'Software Engineering I&II'},
        {'Text': 'Fundamental'},
        {'Text': 'Game Development Technical Experience Research Assistant'},
        {'Text': 'R&B Soft'},
        {'Text': 'Spring 2015'},
        {'Text': 'Present Currently'},
        {'Text': 'a patient satisfaction assessment tool'},
        {'Text': 'self-organizing maps'},
        {'Text': 'multiple layers'},
        {'Text': 'HCAHPS'},
        {'Text': 'Hospital Consumer Assessment'},
        {'Text': 'Healthcare Providers and Systems'},
        {'Text': 'dataset'},
        {'Text': 'recommendations'},
        {'Text': 'hospitals'},
        {'Text': 'a patient flow prediction system'},
        {'Text': 'hospitals'},
        {'Text': 'neural networks'},
        {'Text': 'Implemented genetic algorithm'},
        {'Text': 'a part'},
        {'Text': 'a patient flow optimization system'},
        {'Text': 'Teacher Assistant'},
        {'Text': 'Southern Illinois University Carbondale Fall 2014'},
        {'Text': 'Spring 2015 Supervised'},
        {'Text': 'a weekly lab'},
        {'Text': 'approximately 20 undergraduate students'},
        {'Text': 'Data Structures course'},
        {'Text': 'addition'},
        {'Text': 'the exams'},
        {'Text': 'Assisted graduate'},
        {'Text': 'undergraduate students'},
        {'Text': 'Game Programming Concepts course'},
        {'Text': 'their assignments'},
        {'Text': 'Programmer'},
        {'Text': 'Medrick Game Studio Fall'},
        {'Text': '2011 - Spring 2014 Designed'},
        {'Text': 'a mobile game'},
        {'Text': 'Matchteria'},
        {'Text': 'Android and iOS'},
        {'Text': 'Unity3d'},
        {'Text': 'the award'},
        {'Text': 'The Best Casual Indie Game'},
        {'Text': 'the 3rd Tehran international game festival'},
        {'Text': 'Publication Tabrizi'},
        {'Text': 'T. S.'},
        {'Text': 'Khoie'},
        {'Text': 'M. R.'},
        {'Text': '& Rahimi'},
        {'Text': '2015'},
        {'Text': 'August'},
        {'Text': 'Incremental fuzzy clustering'},
        {'Text': 'an adaptive backgammon game'},
        {'Text': 'Fuzzy Information Processing Society'},
        {'Text': 'NAFIPS'},
        {'Text': '2015 5th World Conference'},
        {'Text': 'Soft Computing'},
        {'Text': 'WConSC'},
        {'Text': '2015 Annual Conference'},
        {'Text': 'the North American'},
        {'Text': 'pp'},
        {'Text': '1-5'},
        {'Text': 'IEEE'},
        {'Text': 'Selected Coursework Projects Click-through Rate Prediction System A project'},
        {'Text': 'Big Data course'},
        {'Text': 'a Kaggle competition'},
        {'Text': 'advantage'},
        {'Text': 'logistic regression'},
        {'Text': 'the likelihood'},
        {'Text': 'an online advertisement'},
        {'Text': 'Motif Search'},
        {'Text': 'Hadoop A project'},
        {'Text': 'course Cloud Computing'},
        {'Text': 'MapReduce algorithm'},
        {'Text': 'a motif'},
        {'Text': 'a DNA sequence'},
        {'Text': 'A learner backgammon player'},
        {'Text': 'An application'},
        {'Text': 'android and iOS'},
        {'Text': 'Unity3d'},
        {'Text': 'an incremental clustering method'},
        {'Text': 'backgammon'},
        {'Text': 'human'},
        {'Text': 'trained devices'},
        {'Text': 'the best teacher'},
        {'Text': 'Space Run'},
        {'Text': 'A physics game'},
        {'Text': 'XNA engine'},
        {'Text': 'Box2D physics engine'},
        {'Text': 'the player'},
        {'Text': 'planets'},
        {'Text': 'the right positions'},
        {'Text': 'their gravity'},
        {'Text': 'a shuttle'},
        {'Text': 'a goal'},
        {'Text': 'Technical Skills Programming Languages'},
        {'Text': 'Java, C#, C, C++, SQL, Shell scripts Tools'},
        {'Text': 'Matlab, R, Unity3D'},
        {'Text': 'CUDA'},
        {'Text': 'MPI'},
        {'Text': 'OpenMP'},
        {'Text': 'Hadoop'},
        {'Text': 'Flash Professional CC'},
        {'Text': 'Photoshop CC'},
        {'Text': 'Visual Paradigm Operating Systems'},
        {'Text': 'Windows'}]}}},
    '_type': 'parsed_resume'},
   {'_id': 'https://s3.amazonaws.com/careers.dataskeptic.com/resumes/unsourced/text/resumes_unsourced_Resume_Data_Scientist.pdf.txt',
    '_index': 'parsed_resume',
    '_score': 1.0,
    '_source': {'education': {'keywords': {'KeyPhrases': [{'Text': 'Orlando, FL'},
        {'Text': 'Dec 2013 University'},
        {'Text': 'Central Florida Boston'},
        {'Text': 'MA Doctor'},
        {'Text': 'Philosophy'},
        {'Text': 'Electrical Engineering'},
        {'Text': 'May 2009 Dissertation Title'},
        {'Text': 'Differential Games'},
        {'Text': 'Multi-agent Systems'},
        {'Text': 'Distributed Information'},
        {'Text': 'Advisors'},
        {'Text': 'Prof'},
        {'Text': 'Zhihua Qu'},
        {'Text': 'Prof'},
        {'Text': 'Marwan A. Simaan Shanghai'},
        {'Text': 'China Boston University Jun 2007 Master'},
        {'Text': 'Science'},
        {'Text': 'Electrical Engineering'},
        {'Text': 'Tongji University Bachelor'},
        {'Text': 'Engineering'},
        {'Text': 'Automation'}]}}},
    '_type': 'parsed_resume'},

In [2453]:
count100 = es.search(index = index_name2, query=
    {
      "_source": 'education.keywords.KeyPhrases.Text',
      "size": 0,
      "aggs": {
        "group_by_coll_conv": {
          "terms": {
            "field": "education.keywords.KeyPhrases.Text.keyword",
            "size" : 500
          },
          "aggs": {
            "count" : {
              "value_count" : 
                { 
                  "field" : "education.keywords.KeyPhrases.Text.keyword" 
                } 
            }
        }
    }
}})

In [2454]:
count100

{'_shards': {'failed': 0, 'successful': 5, 'total': 5},
 'aggregations': {'group_by_coll_conv': {'buckets': [{'count': {'value': 11712},
     'doc_count': 198,
     'key': 'University'},
    {'count': {'value': 7781}, 'doc_count': 170, 'key': 'Science'},
    {'count': {'value': 4486}, 'doc_count': 86, 'key': 'GPA'},
    {'count': {'value': 5846}, 'doc_count': 74, 'key': 'Machine Learning'},
    {'count': {'value': 3077}, 'doc_count': 67, 'key': 'Computer Science'},
    {'count': {'value': 6111}, 'doc_count': 58, 'key': 'Python'},
    {'count': {'value': 2965}, 'doc_count': 57, 'key': 'Technology'},
    {'count': {'value': 6208}, 'doc_count': 55, 'key': 'data'},
    {'count': {'value': 1843}, 'doc_count': 50, 'key': 'Master'},
    {'count': {'value': 3711}, 'doc_count': 48, 'key': 'Engineering'},
    {'count': {'value': 3271}, 'doc_count': 46, 'key': 'Data Mining'},
    {'count': {'value': 3411}, 'doc_count': 46, 'key': 'Los Angeles'},
    {'count': {'value': 2524}, 'doc_count': 41, 'key': 'Ph.D.'},
    {'count': {'value': 2479}, 'doc_count': 40, 'key': 'Mathematics'},
    {'count': {'value': 2218}, 'doc_count': 40, 'key': 'Statistics'},
    {'count': {'value': 2784}, 'doc_count': 39, 'key': 'Southern California'},
    {'count': {'value': 2080}, 'doc_count': 34, 'key': 'Bachelor'},
    {'count': {'value': 2258}, 'doc_count': 30, 'key': 'CA'},
    {'count': {'value': 1626}, 'doc_count': 30, 'key': 'Data Science'},
    {'count': {'value': 2058}, 'doc_count': 30, 'key': 'M.S.'},
    {'count': {'value': 1874}, 'doc_count': 29, 'key': 'Algorithms'},
    {'count': {'value': 1898}, 'doc_count': 29, 'key': 'Economics'},
    {'count': {'value': 1930}, 'doc_count': 29, 'key': 'May 2016'},
    {'count': {'value': 1039}, 'doc_count': 27, 'key': 'Arts'},
    {'count': {'value': 1661}, 'doc_count': 27, 'key': 'California'},
    {'count': {'value': 2460}, 'doc_count': 27, 'key': 'May 2015'},
    {'count': {'value': 2733}, 'doc_count': 26, 'key': 'SQL'},
    {'count': {'value': 2799}, 'doc_count': 25, 'key': '2015'},
    {'count': {'value': 1435},
     'doc_count': 25,
     'key': 'Electrical Engineering'},
    {'count': {'value': 2339}, 'doc_count': 24, 'key': 'Analysis'},
    {'count': {'value': 2644}, 'doc_count': 24, 'key': 'Java'},
    {'count': {'value': 1641}, 'doc_count': 24, 'key': 'Texas'},
    {'count': {'value': 2219}, 'doc_count': 23, 'key': '2014'},
    {'count': {'value': 1468}, 'doc_count': 23, 'key': 'Applied Mathematics'},
    {'count': {'value': 1940}, 'doc_count': 22, 'key': 'Physics'},
    {'count': {'value': 1587}, 'doc_count': 21, 'key': 'B.S.'},
    {'count': {'value': 1890}, 'doc_count': 21, 'key': 'Big Data'},
    {'count': {'value': 1179}, 'doc_count': 21, 'key': 'Business Analytics'},
    {'count': {'value': 1517}, 'doc_count': 21, 'key': 'Illinois'},
    {'count': {'value': 1753}, 'doc_count': 21, 'key': 'Minor'},
    {'count': {'value': 1569}, 'doc_count': 21, 'key': 'PhD'},
    {'count': {'value': 1137}, 'doc_count': 21, 'key': 'Philosophy'},
    {'count': {'value': 1368}, 'doc_count': 21, 'key': 'The University'},
    {'count': {'value': 2774}, 'doc_count': 21, 'key': 'analysis'},
    {'count': {'value': 1834}, 'doc_count': 20, 'key': '2013'},
    {'count': {'value': 1562}, 'doc_count': 20, 'key': 'China'},
    {'count': {'value': 1842}, 'doc_count': 20, 'key': 'Hive'},
    {'count': {'value': 1746}, 'doc_count': 20, 'key': 'India'},
    {'count': {'value': 1881}, 'doc_count': 20, 'key': 'SAS'},
    {'count': {'value': 1044}, 'doc_count': 19, 'key': 'Data Structures'},
    {'count': {'value': 1748}, 'doc_count': 19, 'key': 'Department'},
    {'count': {'value': 1777}, 'doc_count': 18, 'key': 'Beijing'},
    {'count': {'value': 1660}, 'doc_count': 18, 'key': 'Hadoop'},
    {'count': {'value': 1026}, 'doc_count': 17, 'key': 'Dec 2015'},
    {'count': {'value': 2055}, 'doc_count': 17, 'key': 'MATLAB'},
    {'count': {'value': 2338}, 'doc_count': 16, 'key': '2011'},
    {'count': {'value': 1555}, 'doc_count': 16, 'key': 'Introduction'},
    {'count': {'value': 613}, 'doc_count': 16, 'key': 'Masters'},
    {'count': {'value': 1206}, 'doc_count': 16, 'key': 'New York'},
    {'count': {'value': 1084},
     'doc_count': 16,
     'key': 'Science and Technology'},
    {'count': {'value': 1514}, 'doc_count': 16, 'key': 'students'},
    {'count': {'value': 1820}, 'doc_count': 15, 'key': '2012'},
    {'count': {'value': 666}, 'doc_count': 15, 'key': 'MS'},
    {'count': {'value': 2079}, 'doc_count': 15, 'key': 'algorithms'},
    {'count': {'value': 1963}, 'doc_count': 15, 'key': 'reports'},
    {'count': {'value': 1491}, 'doc_count': 14, 'key': 'C, C++'},
    {'count': {'value': 1181}, 'doc_count': 14, 'key': 'Coursera'},
    {'count': {'value': 1760}, 'doc_count': 14, 'key': 'Linux'},
    {'count': {'value': 1130}, 'doc_count': 14, 'key': 'Ph.D'},
    {'count': {'value': 1644}, 'doc_count': 14, 'key': 'Probability'},
    {'count': {'value': 1789}, 'doc_count': 14, 'key': 'clients'},
    {'count': {'value': 1419}, 'doc_count': 13, 'key': '2'},
    {'count': {'value': 1248}, 'doc_count': 13, 'key': '2016'},
    {'count': {'value': 1128},
     'doc_count': 13,
     'key': 'Artificial Intelligence'},
    {'count': {'value': 1211}, 'doc_count': 13, 'key': 'Chennai'},
    {'count': {'value': 1017}, 'doc_count': 13, 'key': 'Data Analysis'},
    {'count': {'value': 1520}, 'doc_count': 13, 'key': 'Matlab'},
    {'count': {'value': 1520}, 'doc_count': 13, 'key': 'MySQL'},
    {'count': {'value': 1250}, 'doc_count': 13, 'key': 'Optimization'},
    {'count': {'value': 1204}, 'doc_count': 13, 'key': 'Pig'},
    {'count': {'value': 1552}, 'doc_count': 13, 'key': 'Tableau'},
    {'count': {'value': 1085}, 'doc_count': 13, 'key': 'USA'},
    {'count': {'value': 1263}, 'doc_count': 13, 'key': 'development'},
    {'count': {'value': 1116}, 'doc_count': 12, 'key': '2008'},
    {'count': {'value': 1170}, 'doc_count': 12, 'key': '2009'},
    {'count': {'value': 1491}, 'doc_count': 12, 'key': '2010'},
    {'count': {'value': 931}, 'doc_count': 12, 'key': 'Aug 2014'},
    {'count': {'value': 903}, 'doc_count': 12, 'key': 'Expected'},
    {'count': {'value': 937},
     'doc_count': 12,
     'key': 'Industrial Engineering'},
    {'count': {'value': 1546}, 'doc_count': 12, 'key': 'May 2014'},
    {'count': {'value': 713}, 'doc_count': 12, 'key': 'Statistics GPA'},
    {'count': {'value': 1313}, 'doc_count': 12, 'key': 'UCLA'},
    {'count': {'value': 616}, 'doc_count': 11, 'key': '1'},
    {'count': {'value': 898},
     'doc_count': 11,
     'key': 'Mathematical Statistics'},
    {'count': {'value': 1423}, 'doc_count': 11, 'key': 'SVM'},
    {'count': {'value': 757}, 'doc_count': 11, 'key': 'Statistical Inference'},
    {'count': {'value': 1564}, 'doc_count': 11, 'key': 'users'},
    {'count': {'value': 533}, 'doc_count': 10, 'key': 'BS'},
    {'count': {'value': 640}, 'doc_count': 10, 'key': 'Business'},
    {'count': {'value': 653}, 'doc_count': 10, 'key': 'Chicago'},
    {'count': {'value': 845}, 'doc_count': 10, 'key': 'Data'},
    {'count': {'value': 795}, 'doc_count': 10, 'key': 'Excel'},
    {'count': {'value': 661}, 'doc_count': 10, 'key': 'May 2010'},
    {'count': {'value': 867}, 'doc_count': 10, 'key': 'May 2012'},
    {'count': {'value': 1261}, 'doc_count': 10, 'key': 'Numerical Analysis'},
    {'count': {'value': 1455}, 'doc_count': 10, 'key': 'PCA'},
    {'count': {'value': 1224}, 'doc_count': 10, 'key': 'Teaching Assistant'},
    {'count': {'value': 1098}, 'doc_count': 10, 'key': 'Windows'},
    {'count': {'value': 1319}, 'doc_count': 10, 'key': 'a team'},
    {'count': {'value': 1055}, 'doc_count': 10, 'key': 'algorithm'},
    {'count': {'value': 696}, 'doc_count': 9, 'key': 'Bayesian Statistics'},
    {'count': {'value': 973}, 'doc_count': 9, 'key': 'CSS'},
    {'count': {'value': 830}, 'doc_count': 9, 'key': 'College'},
    {'count': {'value': 324}, 'doc_count': 9, 'key': 'Electronics'},
    {'count': {'value': 1422}, 'doc_count': 9, 'key': 'Journal'},
    {'count': {'value': 855}, 'doc_count': 9, 'key': 'Jun'},
    {'count': {'value': 566}, 'doc_count': 9, 'key': 'List'},
    {'count': {'value': 342}, 'doc_count': 9, 'key': 'Mechanical Engineering'},
    {'count': {'value': 1082}, 'doc_count': 9, 'key': 'Operations Research'},
    {'count': {'value': 1096}, 'doc_count': 9, 'key': 'Pattern Recognition'},
    {'count': {'value': 1063}, 'doc_count': 9, 'key': 'Regression'},
    {'count': {'value': 1157}, 'doc_count': 9, 'key': 'Research Assistant'},
    {'count': {'value': 897}, 'doc_count': 9, 'key': 'SPSS'},
    {'count': {'value': 784}, 'doc_count': 9, 'key': 'data analysis'},
    {'count': {'value': 1103}, 'doc_count': 9, 'key': 'model'},
    {'count': {'value': 1376}, 'doc_count': 9, 'key': 'the data'},
    {'count': {'value': 959}, 'doc_count': 9, 'key': 'the performance'},
    {'count': {'value': 689}, 'doc_count': 8, 'key': 'Applications'},
    {'count': {'value': 697}, 'doc_count': 8, 'key': 'August 2014'},
    {'count': {'value': 415}, 'doc_count': 8, 'key': 'Bachelors'},
    {'count': {'value': 619}, 'doc_count': 8, 'key': 'Bangalore'},
    {'count': {'value': 293},
     'doc_count': 8,
     'key': 'Business Administration'},
    {'count': {'value': 333}, 'doc_count': 8, 'key': 'Coursework'},
    {'count': {'value': 507}, 'doc_count': 8, 'key': 'December 2015'},
    {'count': {'value': 783}, 'doc_count': 8, 'key': 'Decision Trees'},
    {'count': {'value': 831},
     'doc_count': 8,
     'key': 'Exploratory Data Analysis'},
    {'count': {'value': 612}, 'doc_count': 8, 'key': 'Finance'},
    {'count': {'value': 421}, 'doc_count': 8, 'key': 'Information Technology'},
    {'count': {'value': 943}, 'doc_count': 8, 'key': 'PHP'},
    {'count': {'value': 773}, 'doc_count': 8, 'key': 'R Programming'},
    {'count': {'value': 735}, 'doc_count': 8, 'key': 'Relevant Coursework'},
    {'count': {'value': 613}, 'doc_count': 8, 'key': 'Research'},
    {'count': {'value': 1258}, 'doc_count': 8, 'key': 'accuracy'},
    {'count': {'value': 918}, 'doc_count': 8, 'key': 'models'},
    {'count': {'value': 582}, 'doc_count': 7, 'key': '2006'},
    {'count': {'value': 537}, 'doc_count': 7, 'key': '2007'},
    {'count': {'value': 541}, 'doc_count': 7, 'key': '3.8/4.0'},
    {'count': {'value': 702}, 'doc_count': 7, 'key': '4'},
    {'count': {'value': 237}, 'doc_count': 7, 'key': '4.0/4.0'},
    {'count': {'value': 699}, 'doc_count': 7, 'key': 'Advisor'},
    {'count': {'value': 449},
     'doc_count': 7,
     'key': 'Arizona State University'},
    {'count': {'value': 628}, 'doc_count': 7, 'key': 'B.Sc'},
    {'count': {'value': 318}, 'doc_count': 7, 'key': 'China Bachelor'},
    {'count': {'value': 709}, 'doc_count': 7, 'key': 'Cloud Computing'},
    {'count': {'value': 1082}, 'doc_count': 7, 'key': 'Clustering'},
    {'count': {'value': 301}, 'doc_count': 7, 'key': 'Databases'},
    {'count': {'value': 371}, 'doc_count': 7, 'key': 'Dean'},
    {'count': {'value': 798}, 'doc_count': 7, 'key': 'July 2014'},
    {'count': {'value': 604}, 'doc_count': 7, 'key': 'M.Sc'},
    {'count': {'value': 952}, 'doc_count': 7, 'key': 'MS Excel'},
    {'count': {'value': 955}, 'doc_count': 7, 'key': 'MongoDB'},
    {'count': {'value': 713}, 'doc_count': 7, 'key': 'Nov 2015'},
    {'count': {'value': 578}, 'doc_count': 7, 'key': 'Operating Systems'},
    {'count': {'value': 609}, 'doc_count': 7, 'key': 'Proficient'},
    {'count': {'value': 694}, 'doc_count': 7, 'key': 'Programming'},
    {'count': {'value': 308}, 'doc_count': 7, 'key': 'School'},
    {'count': {'value': 816}, 'doc_count': 7, 'key': 'Thesis'},
    {'count': {'value': 516}, 'doc_count': 7, 'key': 'USC'},
    {'count': {'value': 807}, 'doc_count': 7, 'key': 'implementation'},
    {'count': {'value': 986}, 'doc_count': 7, 'key': 'logistic regression'},
    {'count': {'value': 613}, 'doc_count': 7, 'key': 'machine learning'},
    {'count': {'value': 871}, 'doc_count': 7, 'key': 'terms'},
    {'count': {'value': 344}, 'doc_count': 6, 'key': '2004'},
    {'count': {'value': 734}, 'doc_count': 6, 'key': '6'},
    {'count': {'value': 422}, 'doc_count': 6, 'key': 'Business Intelligence'},
    {'count': {'value': 482}, 'doc_count': 6, 'key': 'C/C++'},
    {'count': {'value': 619}, 'doc_count': 6, 'key': 'Canada'},
    {'count': {'value': 302}, 'doc_count': 6, 'key': 'Computer Engineering'},
    {'count': {'value': 526}, 'doc_count': 6, 'key': 'Computing'},
    {'count': {'value': 435}, 'doc_count': 6, 'key': 'Dec 2015 Master'},
    {'count': {'value': 808}, 'doc_count': 6, 'key': 'Design'},
    {'count': {'value': 313}, 'doc_count': 6, 'key': 'Georgia Institute'},
    {'count': {'value': 737}, 'doc_count': 6, 'key': 'JavaScript'},
    {'count': {'value': 851}, 'doc_count': 6, 'key': 'Logistic Regression'},
    {'count': {'value': 718}, 'doc_count': 6, 'key': 'May 2013'},
    {'count': {'value': 303}, 'doc_count': 6, 'key': 'NY'},
    {'count': {'value': 239}, 'doc_count': 6, 'key': 'North Carolina'},
    {'count': {'value': 558}, 'doc_count': 6, 'key': 'Stanford University'},
    {'count': {'value': 469}, 'doc_count': 6, 'key': 'Statistical Computing'},
    {'count': {'value': 423}, 'doc_count': 6, 'key': 'Statistical Learning'},
    {'count': {'value': 93}, 'doc_count': 6, 'key': 'Statistics University'},
    {'count': {'value': 701},
     'doc_count': 6,
     'key': 'Support Vector Machines'},
    {'count': {'value': 941}, 'doc_count': 6, 'key': 'Tehran'},
    {'count': {'value': 207}, 'doc_count': 6, 'key': 'Theory'},
    {'count': {'value': 543}, 'doc_count': 6, 'key': 'Tools'},
    {'count': {'value': 177}, 'doc_count': 6, 'key': 'UNIVERSITY'},
    {'count': {'value': 443}, 'doc_count': 6, 'key': 'experience'},
    {'count': {'value': 579}, 'doc_count': 6, 'key': 'recommendations'},
    {'count': {'value': 984}, 'doc_count': 6, 'key': 'requirements'},
    {'count': {'value': 664}, 'doc_count': 6, 'key': 'research'},
    {'count': {'value': 846}, 'doc_count': 6, 'key': 'social media'},
    {'count': {'value': 444}, 'doc_count': 6, 'key': 'solutions'},
    {'count': {'value': 568}, 'doc_count': 6, 'key': 'techniques'},
    {'count': {'value': 981}, 'doc_count': 6, 'key': 'the model'},
    {'count': {'value': 685}, 'doc_count': 5, 'key': '2003'},
    {'count': {'value': 375}, 'doc_count': 5, 'key': '3'},
    {'count': {'value': 535}, 'doc_count': 5, 'key': '5'},
    {'count': {'value': 628}, 'doc_count': 5, 'key': 'Accounting'},
    {'count': {'value': 526}, 'doc_count': 5, 'key': 'Apache Pig'},
    {'count': {'value': 405}, 'doc_count': 5, 'key': 'Application'},
    {'count': {'value': 296}, 'doc_count': 5, 'key': 'Applied Statistics'},
    {'count': {'value': 648}, 'doc_count': 5, 'key': 'Apr 2015'},
    {'count': {'value': 575}, 'doc_count': 5, 'key': 'April 2015'},
    {'count': {'value': 573}, 'doc_count': 5, 'key': 'Aug 2013'},
    {'count': {'value': 422}, 'doc_count': 5, 'key': 'Aug 2015'},
    {'count': {'value': 505}, 'doc_count': 5, 'key': 'August 2015'},
    {'count': {'value': 665},
     'doc_count': 5,
     'key': 'Civil and Environmental Engineering'},
    {'count': {'value': 545}, 'doc_count': 5, 'key': 'Classification'},
    {'count': {'value': 625}, 'doc_count': 5, 'key': 'Computer Networks'},
    {'count': {'value': 410}, 'doc_count': 5, 'key': 'Computer Science GPA'},
    {'count': {'value': 343}, 'doc_count': 5, 'key': 'Dallas'},
    {'count': {'value': 537}, 'doc_count': 5, 'key': 'Data Analyst'},
    {'count': {'value': 711}, 'doc_count': 5, 'key': 'Data Analytics'},
    {'count': {'value': 244}, 'doc_count': 5, 'key': 'Data Management'},
    {'count': {'value': 390}, 'doc_count': 5, 'key': 'Data Visualization'},
    {'count': {'value': 626}, 'doc_count': 5, 'key': 'Dec 2014'},
    {'count': {'value': 170}, 'doc_count': 5, 'key': 'EE'},
    {'count': {'value': 738}, 'doc_count': 5, 'key': 'Git'},
    {'count': {'value': 366}, 'doc_count': 5, 'key': 'India GPA'},
    {'count': {'value': 582}, 'doc_count': 5, 'key': 'Information Retrieval'},
    {'count': {'value': 725}, 'doc_count': 5, 'key': 'Institute'},
    {'count': {'value': 473}, 'doc_count': 5, 'key': 'Jan 2015'},
    {'count': {'value': 507}, 'doc_count': 5, 'key': 'June 2014'},
    {'count': {'value': 656}, 'doc_count': 5, 'key': 'June 2015'},
    {'count': {'value': 330}, 'doc_count': 5, 'key': 'Linear Algebra'},
    {'count': {'value': 704}, 'doc_count': 5, 'key': 'MapReduce'},
    {'count': {'value': 615}, 'doc_count': 5, 'key': 'May 2011'},
    {'count': {'value': 596}, 'doc_count': 5, 'key': 'Modeling'},
    {'count': {'value': 735},
     'doc_count': 5,
     'key': 'Principal Component Analysis'},
    {'count': {'value': 531}, 'doc_count': 5, 'key': 'Prof'},
    {'count': {'value': 581}, 'doc_count': 5, 'key': 'Spark'},
    {'count': {'value': 489}, 'doc_count': 5, 'key': 'a model'},
    {'count': {'value': 609}, 'doc_count': 5, 'key': 'children'},
    {'count': {'value': 712}, 'doc_count': 5, 'key': 'decision trees'},
    {'count': {'value': 510},
     'doc_count': 5,
     'key': 'machine learning techniques'},
    {'count': {'value': 594}, 'doc_count': 5, 'key': 'methods'},
    {'count': {'value': 730}, 'doc_count': 5, 'key': 'predictive models'},
    {'count': {'value': 479}, 'doc_count': 5, 'key': 'project'},
    {'count': {'value': 485}, 'doc_count': 5, 'key': 'statistical analysis'},
    {'count': {'value': 500}, 'doc_count': 5, 'key': 'the effectiveness'},
    {'count': {'value': 659}, 'doc_count': 5, 'key': 'the number'},
    {'count': {'value': 641}, 'doc_count': 5, 'key': 'time series'},
    {'count': {'value': 854}, 'doc_count': 5, 'key': 'tools'},
    {'count': {'value': 226}, 'doc_count': 4, 'key': "'08"},
    {'count': {'value': 204}, 'doc_count': 4, 'key': "'12"},
    {'count': {'value': 241}, 'doc_count': 4, 'key': "'14"},
    {'count': {'value': 754}, 'doc_count': 4, 'key': '10'},
    {'count': {'value': 436}, 'doc_count': 4, 'key': '3.7/4.0'},
    {'count': {'value': 56}, 'doc_count': 4, 'key': '3.75/4.00'},
    {'count': {'value': 56}, 'doc_count': 4, 'key': '3.86/4.00'},
    {'count': {'value': 529}, 'doc_count': 4, 'key': '30%'},
    {'count': {'value': 433}, 'doc_count': 4, 'key': '75%'},
    {'count': {'value': 351}, 'doc_count': 4, 'key': '80%'},
    {'count': {'value': 44}, 'doc_count': 4, 'key': '9/2009-12/2012 MSc'},
    {'count': {'value': 293}, 'doc_count': 4, 'key': 'ANOVA'},
    {'count': {'value': 383}, 'doc_count': 4, 'key': 'ASP'},
    {'count': {'value': 674}, 'doc_count': 4, 'key': 'Agile'},
    {'count': {'value': 466}, 'doc_count': 4, 'key': 'Agile methodology'},
    {'count': {'value': 224}, 'doc_count': 4, 'key': 'Aug 2012'},
    {'count': {'value': 191}, 'doc_count': 4, 'key': 'August 2013'},
    {'count': {'value': 86}, 'doc_count': 4, 'key': 'CA Bachelor'},
    {'count': {'value': 314}, 'doc_count': 4, 'key': 'CA GPA'},
    {'count': {'value': 746}, 'doc_count': 4, 'key': 'Civil Engineering'},
    {'count': {'value': 445}, 'doc_count': 4, 'key': 'Computer Vision'},
    {'count': {'value': 476}, 'doc_count': 4, 'key': 'D3'},
    {'count': {'value': 400}, 'doc_count': 4, 'key': 'Dallas, TX'},
    {'count': {'value': 142}, 'doc_count': 4, 'key': 'Data Informatics'},
    {'count': {'value': 447}, 'doc_count': 4, 'key': 'Dept.'},
    {'count': {'value': 259},
     'doc_count': 4,
     'key': 'Digital Signal Processing'},
    {'count': {'value': 279}, 'doc_count': 4, 'key': 'Doctor'},
    {'count': {'value': 159}, 'doc_count': 4, 'key': 'Duke University'},
    {'count': {'value': 99}, 'doc_count': 4, 'key': 'Financial Engineering'},
    {'count': {'value': 84}, 'doc_count': 4, 'key': 'Honors'},
    {'count': {'value': 327}, 'doc_count': 4, 'key': 'Image Processing'},
    {'count': {'value': 162}, 'doc_count': 4, 'key': 'India B.Tech'},
    {'count': {'value': 312}, 'doc_count': 4, 'key': 'Information Systems'},
    {'count': {'value': 755}, 'doc_count': 4, 'key': 'Iran'},
    {'count': {'value': 189}, 'doc_count': 4, 'key': 'January 2016'},

In [2298]:
l_100 = count100['aggregations']['group_by_coll_conv']['buckets']

In [2299]:
keys = []
for i in l_100:
    key = i['key']
    keys.append(key)

In [2300]:
doc_counts = []
for i in l_100:
    doc_count = i['doc_count']
    doc_counts.append(doc_count)

In [2301]:
values = []
for i in l_100:
    value = i['count']['value']
    values.append(value)

In [2302]:
df = pd.DataFrame(
    {'word': keys,
     'doc_count': doc_counts,
     'values': values
    })

In [2303]:
count100['hits']['total']

622

In [2304]:
df['idf'] = np.log(count100['hits']['total']/df['doc_count'])

In [2305]:
df['tf'] = df['values']/sum(df['values'])

In [2306]:
df['tf-idf'] = df['idf']*df['tf']
df.head()

   doc_count  values              word       idf        tf    tf-idf
0        198   11712        University  1.144673  0.031296  0.035824
1        170    7781           Science  1.297142  0.020792  0.026970
2         86    4486               GPA  1.978593  0.011987  0.023718
3         74    5846  Machine Learning  2.128875  0.015621  0.033256
4         67    3077  Computer Science  2.228247  0.008222  0.018321

In [2495]:
pd.options.display.max_rows = 9999

In [2312]:
df_s = df.sort_values(by=['tf','word'], ascending=[False, True])

# all source

In [186]:
sources = ['education', 'summary','experience','projects']

In [187]:
results = []
for element in sources:
    result = es.search(index = index_name2, query=
    {
      "_source": element + '.keywords.KeyPhrases.Text',
      "size": 0,
      "aggs": {
        "group_by_coll_conv": {
          "terms": {
            "field": element + ".keywords.KeyPhrases.Text.keyword",
            "size" : 500
          },
          "aggs": {
            "count" : {
              "value_count" : 
                { 
                  "field" : element + ".keywords.KeyPhrases.Text.keyword"
                } 
            }
        }
    }
}})
    results.append(result)

In [188]:
results_all = []
for i in range(len(results)):
    result_all = results[i]['aggregations']['group_by_coll_conv']['buckets']
    results_all.append(result_all)

In [189]:
dfs = []
for j in range(len(sources)):
    source = sources[j]
    d = results_all[j]
    keys = []
    for i in results_all[j]:
        key = i['key']
        keys.append(key)
    doc_counts = []
    for i in results_all[j]:
        doc_count = i['doc_count']
        doc_counts.append(doc_count)
    values = []
    for i in results_all[j]:
        value = i['count']['value']
        values.append(value)
    aa = pd.DataFrame(
        {'word': keys,
         'doc_count': doc_counts,
         'values': values,
         'source': sources
        })
    dfs.append(aa)

df = pd.concat(dfs)

ValueError: arrays must all be same length

In [190]:
dfs = []
for j in range(len(sources)):
    source = sources[j]
    keys = []
    for i in results_all[j]:
        key = i['key']
        keys.append(key)
    doc_counts = []
    for i in results_all[j]:
        doc_count = i['doc_count']
        doc_counts.append(doc_count)
    values = []
    for i in results_all[j]:
        value = i['count']['value']
        values.append(value)
    aa = pd.DataFrame(
        {'word': keys,
         'doc_count': doc_counts,
         'values': values,
         'source': source
        })
    dfs.append(aa)

df = pd.concat(dfs)
df.reset_index(drop=True)

,doc_count,source,values,word
0,198,education,11712,University
1,170,education,7781,Science
2,86,education,4486,GPA
3,74,education,5846,Machine Learning
4,67,education,3077,Computer Science
5,58,education,6111,Python
6,57,education,2965,Technology
7,55,education,6208,data
8,50,education,1843,Master
9,48,education,3711,Engineering
10,46,education,3271,Data Mining
11,46,education,3411,Los Angeles
12,41,education,2524,Ph.D.
13,40,education,2479,Mathematics
14,40,education,2218,Statistics
15,39,education,2784,Southern California
16,34,education,2080,Bachelor
17,30,education,2258,CA
18,30,education,1626,Data Science
19,30,education,2058,M.S.
20,29,education,1874,Algorithms
21,29,education,1898,Economics
22,29,education,1930,May 2016
23,27,education,1039,Arts
24,27,education,1661,California
25,27,education,2460,May 2015
26,26,education,2733,SQL
27,25,education,2799,2015
28,25,education,1435,Electrical Engineering
29,24,education,2339,Analysis
30,24,education,2644,Java
31,24,education,1641,Texas
32,23,education,2219,2014
33,23,education,1468,Applied Mathematics
34,22,education,1940,Physics
35,21,education,1587,B.S.
36,21,education,1890,Big Data
37,21,education,1179,Business Analytics
38,21,education,1517,Illinois
39,21,education,1753,Minor
40,21,education,1569,PhD
41,21,education,1137,Philosophy
42,21,education,1368,The University
43,21,education,2774,analysis
44,20,education,1834,2013
45,20,education,1562,China
46,20,education,1842,Hive
47,20,education,1746,India
48,20,education,1881,SAS
49,19,education,1044,Data Structures
50,19,education,1748,Department
51,18,education,1777,Beijing
52,18,education,1660,Hadoop
53,17,education,1026,Dec 2015
54,17,education,2055,MATLAB
55,16,education,2338,2011
56,16,education,1555,Introduction
57,16,education,613,Masters
58,16,education,1206,New York
59,16,education,1084,Science and Technology
60,16,education,1514,students
61,15,education,1820,2012
62,15,education,666,MS
63,15,education,2079,algorithms
64,15,education,1963,reports
65,14,education,1491,"C, C++"
66,14,education,1181,Coursera
67,14,education,1760,Linux
68,14,education,1130,Ph.D
69,14,education,1644,Probability
70,14,education,1789,clients
71,13,education,1419,2
72,13,education,1248,2016
73,13,education,1128,Artificial Intelligence
74,13,education,1211,Chennai
75,13,education,1017,Data Analysis
76,13,education,1520,Matlab
77,13,education,1520,MySQL
78,13,education,1250,Optimization
79,13,education,1204,Pig
80,13,education,1552,Tableau
81,13,education,1085,USA
82,13,education,1263,development
83,12,education,1116,2008
84,12,education,1170,2009
85,12,education,1491,2010
86,12,education,931,Aug 2014
87,12,education,903,Expected
88,12,education,937,Industrial Engineering
89,12,education,1546,May 2014
90,12,education,713,Statistics GPA
91,12,education,1313,UCLA
92,11,education,616,1
93,11,education,898,Mathematical Statistics
94,11,education,1423,SVM
95,11,education,757,Statistical Inference
96,11,education,1564,users
97,10,education,533,BS
98,10,education,640,Business
99,10,education,653,Chicago
100,10,education,845,Data
101,10,education,795,Excel
102,10,education,661,May 2010
103,10,education,867,May 2012
104,10,education,1261,Numerical Analysis
105,10,education,1455,PCA
106,10,education,1224,Teaching Assistant
107,10,education,1098,Windows
108,10,education,1319,a team
109,10,education,1055,algorithm
110,9,education,696,Bayesian Statistics
111,9,education,973,CSS
112,9,education,830,College
113,9,education,324,Electronics
114,9,education,1422,Journal
115,9,education,855,Jun
116,9,education,566,List
117,9,education,342,Mechanical Engineering
118,9,education,1082,Operations Research
119,9,education,1096,Pattern Recognition
120,9,education,1063,Regression
121,9,education,1157,Research Assistant
122,9,education,897,SPSS
123,9,education,784,data analysis
124,9,education,1103,model
125,9,education,1376,the data
126,9,education,959,the performance
127,8,education,689,Applications
128,8,education,697,August 2014
129,8,education,415,Bachelors
130,8,education,619,Bangalore
131,8,education,293,Business Administration
132,8,education,333,Coursework
133,8,education,507,December 2015
134,8,education,783,Decision Trees
135,8,education,831,Exploratory Data Analysis
136,8,education,612,Finance
137,8,education,421,Information Technology
138,8,education,943,PHP
139,8,education,773,R Programming
140,8,education,735,Relevant Coursework
141,8,education,613,Research
142,8,education,1258,accuracy
143,8,education,918,models
144,7,education,582,2006
145,7,education,537,2007
146,7,education,541,3.8/4.0
147,7,education,702,4
148,7,education,237,4.0/4.0
149,7,education,699,Advisor
150,7,education,449,Arizona State University
151,7,education,628,B.Sc
152,7,education,318,China Bachelor
153,7,education,709,Cloud Computing
154,7,education,1082,Clustering
155,7,education,301,Databases
156,7,education,371,Dean
157,7,education,798,July 2014
158,7,education,604,M.Sc
159,7,education,952,MS Excel
160,7,education,955,MongoDB
161,7,education,713,Nov 2015
162,7,education,578,Operating Systems
163,7,education,609,Proficient
164,7,education,694,Programming
165,7,education,308,School
166,7,education,816,Thesis
167,7,education,516,USC
168,7,education,807,implementation
169,7,education,986,logistic regression
170,7,education,613,machine learning
171,7,education,871,terms
172,6,education,344,2004
173,6,education,734,6
174,6,education,422,Business Intelligence
175,6,education,482,C/C++
176,6,education,619,Canada
177,6,education,302,Computer Engineering
178,6,education,526,Computing
179,6,education,435,Dec 2015 Master
180,6,education,808,Design
181,6,education,313,Georgia Institute
182,6,education,737,JavaScript
183,6,education,851,Logistic Regression
184,6,education,718,May 2013
185,6,education,303,NY
186,6,education,239,North Carolina
187,6,education,558,Stanford University
188,6,education,469,Statistical Computing
189,6,education,423,Statistical Learning
190,6,education,93,Statistics University
191,6,education,701,Support Vector Machines
192,6,education,941,Tehran
193,6,education,207,Theory
194,6,education,543,Tools
195,6,education,177,UNIVERSITY
196,6,education,443,experience
197,6,education,579,recommendations
198,6,education,984,requirements
199,6,education,664,research
200,6,education,846,social media
201,6,education,444,solutions
202,6,education,568,techniques
203,6,education,981,the model
204,5,education,685,2003
205,5,education,375,3
206,5,education,535,5
207,5,education,628,Accounting
208,5,education,526,Apache Pig
209,5,education,405,Application
210,5,education,296,Applied Statistics
211,5,education,648,Apr 2015
212,5,education,575,April 2015
213,5,education,573,Aug 2013
214,5,education,422,Aug 2015
215,5,education,505,August 2015
216,5,education,665,Civil and Environmental Engineering
217,5,education,545,Classification
218,5,education,625,Computer Networks
219,5,education,410,Computer Science GPA
220,5,education,343,Dallas
221,5,education,537,Data Analyst
222,5,education,711,Data Analytics
223,5,education,244,Data Management
224,5,education,390,Data Visualization
225,5,education,626,Dec 2014
226,5,education,170,EE
227,5,education,738,Git
228,5,education,366,India GPA
229,5,education,582,Information Retrieval
230,5,education,725,Institute
231,5,education,473,Jan 2015
232,5,education,507,June 2014
233,5,education,656,June 2015
234,5,education,330,Linear Algebra
235,5,education,704,MapReduce
236,5,education,615,May 2011
237,5,education,596,Modeling
238,5,education,735,Principal Component Analysis
239,5,education,531,Prof
240,5,education,581,Spark
241,5,education,489,a model
242,5,education,609,children
243,5,education,712,decision trees
244,5,education,510,machine learning techniques
245,5,education,594,methods
246,5,education,730,predictive models
247,5,education,479,project
248,5,education,485,statistical analysis
249,5,education,500,the effectiveness
250,5,education,659,the number
251,5,education,641,time series
252,5,education,854,tools
253,4,education,226,'08
254,4,education,204,'12
255,4,education,241,'14
256,4,education,754,10
257,4,education,436,3.7/4.0
258,4,education,56,3.75/4.00
259,4,education,56,3.86/4.00
260,4,education,529,30%
261,4,education,433,75%
262,4,education,351,80%
263,4,education,44,9/2009-12/2012 MSc
264,4,education,293,ANOVA
265,4,education,383,ASP
266,4,education,674,Agile
267,4,education,466,Agile methodology
268,4,education,224,Aug 2012
269,4,education,191,August 2013
270,4,education,86,CA Bachelor
271,4,education,314,CA GPA
272,4,education,746,Civil Engineering
273,4,education,445,Computer Vision
274,4,education,476,D3
275,4,education,400,"Dallas, TX"
276,4,education,142,Data Informatics
277,4,education,447,Dept.
278,4,education,259,Digital Signal Processing
279,4,education,279,Doctor
280,4,education,159,Duke University
281,4,education,99,Financial Engineering
282,4,education,84,Honors
283,4,education,327,Image Processing
284,4,education,162,India B.Tech
285,4,education,312,Information Systems
286,4,education,755,Iran
287,4,education,189,January 2016
288,4,education,325,June 2012
289,4,education,637,KNN
290,4,education,475,Linear Models
291,4,education,348,Linear Regression
292,4,education,348,MPI
293,4,education,387,MS Office
294,4,education,231,Machine learning
295,4,education,569,Major
296,4,education,317,Management
297,4,education,178,May 2016 Master
298,4,education,118,Multivariate Analysis
299,4,education,186,Natural Language Processing
300,4,education,225,Neural Networks
301,4,education,196,Northeastern University
302,4,education,559,Nov 2013
303,4,education,624,Oct 2015
304,4,education,459,Oracle
305,4,education,271,Pittsburgh
306,4,education,294,Probability Theory
307,4,education,465,Proceedings
308,4,education,531,Programming Languages
309,4,education,495,Publications
310,4,education,478,Random Forest
311,4,education,401,SAS Enterprise Miner
312,4,education,452,Seattle
313,4,education,160,St. Louis
314,4,education,318,Statistical Methods
315,4,education,338,Text Mining
316,4,education,223,Visualization
317,4,education,408,Weka
318,4,education,629,Wuhan
319,4,education,344,XML
320,4,education,671,classification
321,4,education,320,company
322,4,education,662,content
323,4,education,556,customers
324,4,education,440,design
325,4,education,323,different types
326,4,education,574,part
327,4,education,228,patients
328,4,education,585,pp
329,4,education,423,predictive modeling
330,4,education,393,product
331,4,education,568,random forest
332,4,education,574,sales
333,4,education,489,teams
334,4,education,599,the help
335,4,education,573,the purpose
336,4,education,402,unstructured data
337,4,education,467,workflows
338,3,education,222,'15
339,3,education,33,1/2013-6/2016 PhD
340,3,education,340,10%
341,3,education,307,12
342,3,education,153,12 University
343,3,education,273,15 simulated combat training exercises
344,3,education,279,15%
345,3,education,567,19
346,3,education,539,1st
347,3,education,282,2005
348,3,education,143,2014 Bachelor
349,3,education,121,2014 University
350,3,education,371,3 years
351,3,education,196,3.5/4.0
352,3,education,93,3.51
353,3,education,138,3.62/4.00
354,3,education,164,3.67
355,3,education,352,3.7
356,3,education,67,3.8
357,3,education,318,3.9/4.0
358,3,education,461,7%
359,3,education,311,8
360,3,education,435,9
361,3,education,655,95
362,3,education,455,A/B testing
363,3,education,95,Aerospace Engineering
364,3,education,448,Algorithm
365,3,education,246,Analytics
366,3,education,211,Applied Linear Regression
367,3,education,298,Applied Mathematics GPA
368,3,education,319,Applied Natural Language Processing
369,3,education,197,Applied Probability
370,3,education,197,Applied Time Series
371,3,education,434,Assisted
372,3,education,92,Aug 2008
373,3,education,110,B.E.
374,3,education,383,Bank
375,3,education,215,CGPA
376,3,education,220,"California, Los Angeles Los Angeles"
377,3,education,221,Chemical Engineering
378,3,education,220,College Station
379,3,education,68,Computer Science [GPA
380,3,education,156,Cumulative GPA
381,3,education,349,Data Scientist
382,3,education,286,December 2013
383,3,education,57,Design and Analysis
384,3,education,380,Eclipse
385,3,education,212,Finance and Economics
386,3,education,205,France
387,3,education,195,Hons
388,3,education,104,IBM
389,3,education,63,India Bachelor
390,3,education,603,Japan
391,3,education,237,July 2012
392,3,education,193,June 2013
393,3,education,42,Kakatiya University
394,3,education,424,LDA
395,3,education,99,Los Angeles Master
396,3,education,274,March 2014
397,3,education,320,Maryland
398,3,education,363,Mathematical Modeling
399,3,education,79,May 2005
400,3,education,306,New Mexico
401,3,education,42,North Carolina Charlotte
402,3,education,548,Pandas
403,3,education,322,Project Management
404,3,education,376,Random Forests
405,3,education,650,Research Fellow
406,3,education,265,San Francisco
407,3,education,180,Signal Processing
408,3,education,295,Simulation
409,3,education,261,Software Engineering
410,3,education,309,Texas A&M University
411,3,education,257,Tianjin
412,3,education,350,Time Series
413,3,education,390,a part
414,3,education,290,a web
415,3,education,251,an accuracy
416,3,education,208,data mining
417,3,education,418,datasets
418,3,education,347,estimation
419,3,education,425,images
420,3,education,366,insights
421,3,education,249,physics
422,3,education,314,progress
423,3,education,174,publications
424,3,education,378,testing
425,3,education,406,the analysis
426,3,education,480,the impact
427,3,education,281,the results
428,3,education,275,time series analysis
429,2,education,462,#ED33C-0949
430,2,education,462,#H33G-1475
431,2,education,462,#H34D-03. 2 [13] Sara Sadri
432,2,education,462,#H53J-1547
433,2,education,333,' award
434,2,education,261,' behavior
435,2,education,320,' current operation
436,2,education,133,' experience
437,2,education,320,' financial status
438,2,education,264,' liquidity position
439,2,education,61,'11
440,2,education,116,'12 Bachelor
441,2,education,110,'12 Masters
442,2,education,434,+ Symposium Assistant
443,2,education,434,0.30379
444,2,education,462,01/05 03/05 09/98 07/02 University
445,2,education,462,03/12 07/14 06/12 08/12 Scientist
446,2,education,462,04/08 08/08 Guest Researcher
447,2,education,462,07/11 02/12 University
448,2,education,462,09/03 08/05 Ph.D.
449,2,education,462,09/05 06/10 University
450,2,education,462,1 09/03 08/05 Research Assistant
451,2,education,434,1 PUBLICATION
452,2,education,258,1 year
453,2,education,434,1/40
454,2,education,370,10 teaching assistants
455,2,education,320,10.2013
456,2,education,434,100 selected student leaders
457,2,education,362,11
458,2,education,462,11/10 06/11 07/10 10/10 Postdoctoral Research ...
459,2,education,274,11/12 11/13
460,2,education,146,12 Mississippi State University Master
461,2,education,462,"12, 27612798"
462,2,education,434,12/124
463,2,education,246,14
464,2,education,462,14th Global Conference
465,2,education,434,150+ scripts
466,2,education,462,17-20 October
467,2,education,112,17.15/20
468,2,education,181,1998
469,2,education,112,1999-2004 University
470,2,education,462,1] S. Sadri
471,2,education,434,2/16
472,2,education,269,20%
473,2,education,320,200 dimensions
474,2,education,160,2001
475,2,education,52,2007 - May
476,2,education,26,2007 BS
477,2,education,26,2007 to 2014 MS
478,2,education,40,2007-2012 University
479,2,education,112,2008-2011 Carried
480,2,education,434,2010 Annual Meeting
481,2,education,434,2010 Annual Polymer Conference
482,2,education,29,2010 Resume data
483,2,education,128,2010-2011 Member
484,2,education,30,2010-2014
485,2,education,434,2011 Annual Polymer Conference
486,2,education,52,2011 Concentration
487,2,education,320,2011&2012
488,2,education,15,2012 Resume data
489,2,education,71,2013 - B.S.
490,2,education,52,2013 - May
491,2,education,146,2013 Minshan Cui
492,2,education,245,2013-2015
493,2,education,112,2013-2015 2011-2014 Multimodal Dynamic Freight...
494,2,education,128,2014 - 2015 International Student Scholarship ...
495,2,education,52,2014 Concentration
496,2,education,146,2014 Minshan Cui
497,2,education,37,2014- May
498,2,education,40,2014-2015 Summer 2013 University
...,...,...,...,...
1501,57,projects,4993,data
1502,30,projects,2316,SVM
1503,28,projects,2254,Java
1504,27,projects,2538,the data
1505,25,projects,2841,University
1506,25,projects,2074,algorithms
1507,20,projects,1485,May 2015
1508,20,projects,1732,MySQL
1509,18,projects,1170,Random Forest
1510,17,projects,1284,Matlab
1511,17,projects,1370,users
1512,16,projects,1727,India
1513,16,projects,1225,Logistic Regression
1514,16,projects,1148,Tableau
1515,15,projects,975,Hadoop
1516,15,projects,925,MATLAB
1517,14,projects,1345,Machine Learning
1518,14,projects,1456,a team
1519,13,projects,1145,SAS
1520,13,projects,1568,accuracy
1521,13,projects,1257,features
1522,13,projects,1328,the performance
1523,12,projects,934,2015
1524,12,projects,1093,Neural Networks
1525,12,projects,1245,the results
1526,11,projects,921,Analysis
1527,11,projects,751,MapReduce
1528,11,projects,1328,analysis
1529,11,projects,1029,customers
1530,11,projects,1067,this project
1531,10,projects,902,1
1532,10,projects,965,2014
1533,10,projects,1022,Data Mining
1534,10,projects,713,Decision Tree
1535,10,projects,960,a predictive model
1536,10,projects,681,the application
1537,10,projects,886,time
1538,9,projects,819,D3
1539,9,projects,455,SQL
1540,9,projects,884,a database
1541,9,projects,730,information
1542,9,projects,948,logistic regression
1543,9,projects,817,random forest
1544,9,projects,1025,the number
1545,8,projects,807,3
1546,8,projects,374,April 2015
1547,8,projects,586,Dec 2014
1548,8,projects,555,Hive
1549,8,projects,698,Kaggle
1550,8,projects,779,Principal Component Analysis
1551,8,projects,907,algorithm
1552,8,projects,734,machine learning
1553,8,projects,823,model
1554,8,projects,660,python
1555,8,projects,519,the probability
1556,7,projects,780,2
1557,7,projects,857,2012
1558,7,projects,956,Data
1559,7,projects,541,Design
1560,7,projects,592,Random Forests
1561,7,projects,672,Spark
1562,7,projects,991,USA
1563,7,projects,756,an algorithm
1564,7,projects,486,performance
1565,7,projects,534,the model
1566,6,projects,497,80%
1567,6,projects,502,Apache Spark
1568,6,projects,399,Aug 2015
1569,6,projects,496,Classification
1570,6,projects,718,Department
1571,6,projects,536,Excel
1572,6,projects,614,JavaScript
1573,6,projects,752,K-means
1574,6,projects,812,Los Angeles
1575,6,projects,647,MongoDB
1576,6,projects,523,Na ve Bayes
1577,6,projects,658,PCA
1578,6,projects,481,Prediction
1579,6,projects,523,San Francisco
1580,6,projects,620,Technology
1581,6,projects,490,Tools
1582,6,projects,712,a business
1583,6,projects,513,a user
1584,6,projects,420,an accuracy
1585,6,projects,567,day
1586,6,projects,458,factors
1587,6,projects,554,movies
1588,6,projects,700,number
1589,6,projects,634,research
1590,6,projects,407,sentiment analysis
1591,6,projects,789,techniques
1592,6,projects,428,the company
1593,6,projects,519,the dataset
1594,6,projects,552,the help
1595,6,projects,606,the user
1596,5,projects,470,'14
1597,5,projects,328,Android
1598,5,projects,302,Apache Pig
1599,5,projects,517,August 2015
1600,5,projects,557,CA
1601,5,projects,247,Capstone Project
1602,5,projects,721,Company
1603,5,projects,437,Data Science
1604,5,projects,465,Decision Trees
1605,5,projects,611,Goal
1606,5,projects,384,Implementation
1607,5,projects,506,LDA
1608,5,projects,408,Linear Regression
1609,5,projects,595,Machine Learning techniques
1610,5,projects,308,Oct 2015
1611,5,projects,418,Optimization
1612,5,projects,427,PHP
1613,5,projects,391,Recommendation System
1614,5,projects,467,Regression
1615,5,projects,207,Statistical Analysis
1616,5,projects,356,Time Series Analysis
1617,5,projects,540,images
1618,5,projects,470,js
1619,5,projects,483,machine learning algorithms
1620,5,projects,303,patterns
1621,5,projects,428,ratings
1622,5,projects,437,reports
1623,5,projects,529,the analysis
1624,5,projects,254,the team
1625,5,projects,342,the tweets

In [22]:
results[0]['hits']['total']

622

In [2538]:

dfs = []
for j in range(len(sources)):
    source = sources[j]
    keys = []
    for i in results_all[j]:
        key = i['key']
        keys.append(key)
    doc_counts = []
    for i in results_all[j]:
        doc_count = i['doc_count']
        doc_counts.append(doc_count)
    values = []
    for i in results_all[j]:
        value = i['count']['value']
        values.append(value)
    for i in results_all[j]:
        idfs = np.log([results[0]['hits']['total']/x for x in doc_counts]).tolist()
    aa = pd.DataFrame(
        {'word': keys,
         'doc_count': doc_counts,
         'values': values,
         'source': source,
         'idf':idfs
        })
    dfs.append(aa)

df = pd.concat(dfs)
df.reset_index(drop=True)

In [23]:
df['values']/sum(df['values'])
dfs = []
for j in range(len(sources)):
    source = sources[j]
    keys = []
    for i in results_all[j]:
        key = i['key']
        keys.append(key)
    doc_counts = []
    for i in results_all[j]:
        doc_count = i['doc_count']
        doc_counts.append(doc_count)
    values = []
    for i in results_all[j]:
        value = i['count']['value']
        values.append(value)
    for i in results_all[j]:
        idfs = np.log([results[0]['hits']['total']/x for x in doc_counts]).tolist()
    for i in results_all[j]:
        tf = [x/sum(values) for x in values]
    for i in result_all[j]:
        tf_idf = [a*b for a,b in zip(tf,idfs)]
    aa = pd.DataFrame(
        {'word': keys,
         'doc_count': doc_counts,
         'values': values,
         'source': source,
         'idf':idfs,
         'tf':tf,
         'tf_idf':tf_idf
        })
    dfs.append(aa)

df = pd.concat(dfs)
df.reset_index(drop=True,inplace = True)
df= df.sort_values(by=['tf','word'], ascending=[False, True])

In [179]:
pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [29]:
df.sort_values('word')

,doc_count,idf,source,tf,tf_idf,values,word
1819,2,5.739793,projects,0.000934,0.005360,200,"""AVR Microcontrollers"
1820,2,5.739793,projects,0.000934,0.005360,200,"""Dynamical Systems"
1821,2,5.739793,projects,0.000934,0.005360,200,"""Linear and Nonlinear Kalman Filter"
1822,2,5.739793,projects,0.000934,0.005360,200,"""Linear and Nonlinear Kalman Filters"
1823,2,5.739793,projects,0.000934,0.005360,200,"""Signal Processing"
1824,2,5.739793,projects,0.000934,0.005360,200,"""Single-channel and Multi-channel Blind"
429,2,5.739793,education,0.001235,0.007086,462,#ED33C-0949
430,2,5.739793,education,0.001235,0.007086,462,#H33G-1475
431,2,5.739793,education,0.001235,0.007086,462,#H34D-03. 2 [13] Sara Sadri
432,2,5.739793,education,0.001235,0.007086,462,#H53J-1547
1825,2,5.739793,projects,0.000588,0.003377,126,$1.6M
1826,2,5.739793,projects,0.002012,0.011551,431,"$225,000"
1684,3,5.334328,projects,0.000756,0.004035,162,&TRAININGS Independent Research
433,2,5.739793,education,0.000890,0.005107,333,' award
1685,3,5.334328,projects,0.001475,0.007871,316,' award
434,2,5.739793,education,0.000697,0.004003,261,' behavior
1827,2,5.739793,projects,0.001256,0.007209,269,' competitors
435,2,5.739793,education,0.000855,0.004908,320,' current operation
550,4,5.046646,summary,0.001046,0.005277,231,' experience
436,2,5.739793,education,0.000355,0.002040,133,' experience
437,2,5.739793,education,0.000855,0.004908,320,' financial status
1686,3,5.334328,projects,0.002115,0.011283,453,' information
438,2,5.739793,education,0.000705,0.004049,264,' liquidity position
1828,2,5.739793,projects,0.000374,0.002144,80,' preferences
1829,2,5.739793,projects,0.001298,0.007451,278,'07
253,4,5.046646,education,0.000604,0.003048,226,'08
1830,2,5.739793,projects,0.001018,0.005843,218,'10 - Apr
1687,3,5.334328,projects,0.001363,0.007273,292,'11
439,2,5.739793,education,0.000163,0.000936,61,'11
1831,2,5.739793,projects,0.001018,0.005843,218,'11 - Apr
...,...,...,...,...,...,...,...
1680,4,5.046646,projects,0.002503,0.012630,536,time series analysis
681,4,5.046646,summary,0.003408,0.017201,753,tools
252,5,4.823502,education,0.002282,0.011007,854,tools
1157,11,4.035045,experience,0.002220,0.008957,1324,tools
1407,5,4.823502,experience,0.000627,0.003025,374,topics
1626,5,4.823502,projects,0.002428,0.011712,520,topics
769,3,5.334328,summary,0.002929,0.015622,647,transformation
770,3,5.334328,summary,0.002929,0.015622,647,transformations
1091,16,3.660351,experience,0.002257,0.008260,1346,trends
1269,7,4.487030,experience,0.001008,0.004521,601,tweets
336,4,5.046646,education,0.001074,0.005421,402,unstructured data
1408,5,4.823502,experience,0.000708,0.003413,422,unstructured data
1334,6,4.641181,experience,0.000952,0.004420,568,user
1681,4,5.046646,projects,0.001046,0.005278,224,user
1013,35,2.877592,experience,0.006261,0.018015,3734,users
96,11,4.035045,education,0.004179,0.016863,1564,users
1511,17,3.599727,projects,0.006397,0.023027,1370,users
1270,7,4.487030,experience,0.001356,0.006086,809,validation
1682,4,5.046646,projects,0.001480,0.007470,317,variables
771,3,5.334328,summary,0.002929,0.015622,647,various machine
772,3,5.334328,summary,0.001190,0.006350,263,view
1335,6,4.641181,experience,0.001509,0.007003,900,views
1409,5,4.823502,experience,0.000659,0.003178,393,visualization
1410,5,4.823502,experience,0.001108,0.005346,661,visualizations
1818,3,5.334328,projects,0.001718,0.009166,368,which industry
773,3,5.334328,summary,0.002929,0.015622,647,which industry
1683,4,5.046646,projects,0.001998,0.010086,428,wine
774,3,5.334328,summary,0.002929,0.015622,647,workflows
1336,6,4.641181,experience,0.001273,0.005906,759,workflows
337,4,5.046646,education,0.001248,0.006298,467,workflows

In [31]:
df2 = df

In [46]:
df2['word'] = [x.lower() for x in df2['word']]

In [191]:
df3 = pd.DataFrame(df2.groupby(['word'])['doc_count'].sum())

In [192]:
df3.columns = ['count']

In [193]:
df3 = df3.reset_index()

In [214]:
df3.head()

                                   word  count
0                 "avr microcontrollers      2
1                    "dynamical systems      2
2   "linear and nonlinear kalman filter      2
3  "linear and nonlinear kalman filters      2
4                    "signal processing      2

In [215]:
def num_there(s):
    return any(i.isdigit() for i in s)

In [216]:
word_list = df3['word'].tolist()

In [217]:
df_num = pd.DataFrame([num_there(i) for i in word_list])

In [219]:
df4 = pd.concat([df3,df_num], axis=1)

In [220]:
df_no_num = df4[df4.loc[:][0]==False]

In [221]:
df_no_num .reset_index(drop=True, inplace=True)

In [113]:
# ''.join(filter(str.isalnum, string))

In [ ]:
import re
re.sub(r'\W+', ' ', string)

In [223]:
def remove_spe_chara(string):

    return re.sub(r'\W+', ' ', string)

In [224]:
no_spec_list = df_no_num['word'].tolist()

In [225]:
df_no_spe = pd.DataFrame([remove_spe_chara(i) for i in no_spec_list])

In [226]:
df_no_spe=df_no_spe.rename(columns = {0:'word2'})

In [229]:
df_final = pd.concat([df_no_num,df_no_spe],axis=1)

In [207]:
df_final=pd.DataFrame(df_final.groupby(['word2'])['word2'].count())

In [209]:
df_final = df_final.reset_index()

In [208]:
df_final.columns = ['count']

In [231]:
df_final.to_clipboard()

In [ ]:
# save to parquet
# save to s3

In [2557]:
filename = 'terms.parquet'

In [ ]:
df.to_parquet(filename)

In [2559]:
s3.Bucket(bucketname).upload_file(filename,'sys/parsed-keywords_v1.parquet')